server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /sky-engine-remote/stellarium/ {
    proxy_pass https://data.stellarium.org/;
    proxy_set_header Host data.stellarium.org;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /assets/ {
    expires 1y;
    add_header Cache-Control "public";
  }
}
