/** Local admission guards before using pinned upstream normalizers. */
export function validPoint(latitude,longitude){return Number.isFinite(latitude)&&Math.abs(latitude)<=90&&Number.isFinite(longitude)&&Math.abs(longitude)<=180;}
export function admitAircraft(snapshot,now=Date.now()){
  if(!Number.isFinite(snapshot.time)||Math.abs(now-snapshot.time*1000)>120000)throw Error('Aircraft timestamp unavailable or stale');
  return snapshot.states.filter(row=>/^[0-9a-f]{6}$/i.test(row[0])&&validPoint(row[6],row[5])&&Number.isFinite(row[13])&&row[13]>=-500&&row[13]<=100000&&Number.isFinite(row[3])&&now-row[3]*1000<120000);
}
export function weatherPayloadValid(payload){const c=payload?.current;return !!c&&typeof c.temperature_2m==='number'&&Number.isFinite(c.temperature_2m)&&typeof c.time==='string'&&Number.isFinite(Date.parse(/Z$/.test(c.time)?c.time:c.time+'Z'))&&new Date(/Z$/.test(c.time)?c.time:c.time+'Z').toISOString().slice(0,16)===c.time.slice(0,16);}
export function validTleLine(line,prefix){if(line.length!==69||!line.startsWith(prefix+' ')||!/\d/.test(line[68]))return false;let sum=0;for(const c of line.slice(0,68))sum+=/\d/.test(c)?Number(c):c==='-'?1:0;return sum%10===Number(line[68]);}
export function tleRecords(text){const lines=text.split(/\r?\n/).map(s=>s.trimEnd()).filter(Boolean);const records=[];for(let i=0;i+2<lines.length;i++){const [name,line1,line2]=lines.slice(i,i+3);if(validTleLine(line1,'1')&&validTleLine(line2,'2')&&line1.slice(2,7)===line2.slice(2,7)){records.push({name:name.replace(/^0 /,''),id:line1.slice(2,7).trim(),line1,line2});i+=2;}}return records.slice(0,100);}
export async function readCapped(response,cap=2_000_000){if(!response.ok||!response.body)throw Error('Source unavailable');const reader=response.body.getReader();const chunks=[];let size=0;try{while(true){const {value,done}=await reader.read();if(done)break;size+=value.byteLength;if(size>cap)throw Error('Response exceeds cap');chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}return new TextDecoder().decode(bytes);}finally{await reader.cancel();}}
