import {test,expect,type Page} from '@playwright/test'
const names={earthquakes:'Earthquakes · M2.5+ · past day','fire-perimeters':'Fire perimeters · recent subset','weather-radar':'Radar reflectivity · CONUS'}
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=','base64')
async function setup(page:Page,fail=false){
 await page.addInitScript(()=>sessionStorage.setItem('oras.workspace.ui.v1',JSON.stringify({version:1,pin:true,context:'tonight',layers:['oras-site']})))
 const state={fail};await page.route('**/api/earth/**',async route=>{const id=new URL(route.request().url()).pathname.split('/').at(-1)!;if(!['earthquakes','fire-perimeters','weather-radar','radar-image'].includes(id)){await route.continue();return}if(state.fail){await route.fulfill({status:503,json:{detail:'Declared unavailable fixture'}});return}const stamp=new Date().toISOString();if(id==='radar-image'){await route.fulfill({body:png,contentType:'image/png'});return}const record={id:'declared-fixture',name:id==='earthquakes'?'Declared earthquake fixture':'Declared fire fixture',lat:41.4,lon:-79.7,occurredAt:id==='earthquakes'?stamp:null,updatedAt:stamp,magnitude:id==='earthquakes'?5.2:null,depthKm:id==='earthquakes'?10:null,acres:id==='fire-perimeters'?25:null,containedPct:id==='fire-perimeters'?35:null,polygons:id==='fire-perimeters'?[[[[-79.8,41.3],[-79.6,41.3],[-79.6,41.5],[-79.8,41.3]]]]:null};await route.fulfill({json:id==='weather-radar'?{schemaVersion:1,product:'radar',temporalMode:'CURRENT_SNAPSHOT',source:'NOAA/NWS nowCOAST',latest:stamp,times:[stamp],bounds:{west:-130,south:20,east:-60,north:55},fetchedAt:stamp,tileSize:256,maxLevel:6,tilingScheme:'geographic'}:{schemaVersion:1,kind:id,temporalMode:id==='earthquakes'?'EVENT_FEED':'CURRENT_SNAPSHOT',source:id==='earthquakes'?'U.S. Geological Survey':'NIFC/WFIGS',observedAt:stamp,fetchedAt:stamp,records:[record],limited:id==='fire-perimeters'}})})
 return state
}
async function ready(page:Page,mode='earth'){await expect(page.locator(`[data-runtime-mode=${mode}][data-runtime-status=ready]`)).toBeVisible({timeout:90000});await expect(page.locator('iframe')).toHaveCount(1)}
async function panel(page:Page){await page.getByRole('button',{name:'Layers',exact:true}).click()}
async function select(page:Page,id:string){const earth=page.frames().find(f=>f.url().includes('/earth-runtime/'))!;let target:any;await expect.poll(async()=>{target=await earth.evaluate(layer=>(window as any).orasEarthVisibleTargets().find((row:any)=>row.kind===layer),id);return !!target}).toBe(true);await earth.locator('canvas').first().click({position:{x:target.x,y:target.y}});return earth}
for(const mobile of [false,true])test(`declared event/surface fixtures: enable select Focus source status disable and 44px controls ${mobile?'mobile':'desktop'}`,async({page})=>{
 test.setTimeout(180000);await page.setViewportSize(mobile?{width:390,height:844}:{width:1440,height:900});await setup(page);await page.goto('/earth');await ready(page);await panel(page);await page.screenshot({path:`../output/playwright/earth-expansion/${mobile?'mobile':'desktop'}-layers.png`});
 for(const id of ['earthquakes','fire-perimeters','weather-radar'] as const){
  const toggle=page.getByRole('switch',{name:names[id],exact:true}),box=await toggle.boundingBox();expect(box!.height).toBeGreaterThanOrEqual(44);await toggle.click();await expect(page.locator(`.ws-layer[data-layer-id=${id}]`)).toContainText(id==='earthquakes'?'Recent event feed':'Current snapshot',{timeout:20000});await page.screenshot({path:`../output/playwright/earth-expansion/${mobile?'mobile':'desktop'}-${id}-enabled.png`});
  await (mobile?page.getByRole('button',{name:'Close sheet',exact:true}):page.getByRole('region',{name:'Earth layers'}).getByRole('button',{name:'Close panel',exact:true})).click();const earth=await select(page,id);await expect(page.getByText(id==='weather-radar'?'CONUS radar reflectivity':id==='earthquakes'?'Declared earthquake fixture':'Declared fire fixture').first()).toBeVisible();await page.getByRole('button',{name:'Focus',exact:true}).click();await expect.poll(()=>earth.evaluate(()=>(window as any).orasEarthDiagnostics().cameraHeightM)).toBeLessThan(id==='weather-radar'?6000000:100000);await page.screenshot({path:`../output/playwright/earth-expansion/${mobile?'mobile':'desktop'}-${id}-selected.png`});await page.getByRole('button',{name:'Deselect',exact:true}).click();await earth.locator('#home').evaluate((node:any)=>node.click());await panel(page);await page.getByRole('switch',{name:names[id],exact:true}).click();await expect(page.locator(`.ws-layer[data-layer-id=${id}]`)).toContainText('Off');await page.reload();await ready(page);await panel(page);
 }
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
for(const mobile of [false,true])test(`all new providers unavailable preserve Earth readiness; retry restores a source ${mobile?'mobile':'desktop'}`,async({page})=>{test.setTimeout(120000);await page.setViewportSize(mobile?{width:390,height:844}:{width:1440,height:900});const state=await setup(page,true);await page.goto('/earth');await ready(page);await panel(page);for(const id of Object.keys(names) as (keyof typeof names)[]){await page.getByRole('switch',{name:names[id],exact:true}).click();await expect(page.locator(`.ws-layer[data-layer-id=${id}]`)).toContainText('Unavailable',{timeout:20000})}await ready(page);await page.screenshot({path:`../output/playwright/earth-expansion/${mobile?'mobile':'desktop'}-unavailable.png`});state.fail=false;await page.getByRole('button',{name:'Retry earthquakes',exact:true}).click();await expect(page.locator('.ws-layer[data-layer-id=earthquakes]')).toContainText('Recent event feed')})
test('representative Sky exact link and Sky Earth Sky serial lifetime',async({page})=>{test.setTimeout(180000);await setup(page);const data=await(await page.request.get('/api/tonight?date=2026-10-03')).json(),identity=data.data.top_opportunities[0],target=data.data.targets.find((row:any)=>row.catalog===identity.catalog&&row.source_id===identity.source_id&&row.model===identity.model);const link=new URL(target.sky_engine_url,'http://oras.test');link.searchParams.set('date','2026-10-03T02:00:00Z');await page.goto('/sky-engine?'+link.searchParams);await ready(page,'sky');await expect(page.getByRole('region',{name:'Selected object'})).toContainText(target.name,{timeout:30000});const sky=await page.locator('iframe').elementHandle();await page.getByRole('tab',{name:'Earth',exact:true}).click();await ready(page);expect(await sky!.evaluate(n=>n.isConnected)).toBe(false);const earth=await page.locator('iframe').elementHandle();await page.getByRole('tab',{name:'Sky',exact:true}).click();await ready(page,'sky');expect(await earth!.evaluate(n=>n.isConnected)).toBe(false)})
