import {test,expect,type Page} from '@playwright/test'
const ready=async(page:Page,mode:string)=>{await expect(page.locator(`[data-runtime-mode=${mode}][data-runtime-status=ready]`)).toBeVisible({timeout:90000});await expect(page.locator('iframe')).toHaveCount(1)}
async function pin(page:Page){if((await page.viewportSize())!.width<768){await page.getByRole('button',{name:'Workspace menu'}).click();await page.getByRole('region',{name:'Workspace menu'}).getByRole('button',{name:'Pin controls',exact:true}).click();await page.keyboard.press('Escape')}else await page.getByRole('button',{name:'Pin controls',exact:true}).click()}
async function layerPanel(page:Page){await page.getByRole('button',{name:'Layers',exact:true}).click();await expect(page.getByRole('region',{name:'Earth layers'}).last()).toBeVisible()}
for(const [label,width,height] of [['desktop',1440,900],['tablet',1024,768],['mobile',390,844]] as const){
 test.describe(label,()=>{test.use({viewport:{width,height},hasTouch:label==='mobile',isMobile:label==='mobile'});
 test(`workspace controls and serial history ${label}`,async({page})=>{
  test.setTimeout(240000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?date=2026-10-03T02%3A00%3A00Z');await ready(page,'sky');await pin(page);await expect(page.getByRole('tab',{name:'Sky',exact:true})).toHaveAttribute('aria-selected','true');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  if(label==='mobile'){await page.getByRole('button',{name:'Tonight',exact:true}).click()}else await page.getByRole('button',{name:'Tonight',exact:true}).click();await expect(page.getByRole('heading',{name:'Tonight at ORAS'})).toBeVisible();
  await page.getByRole('tab',{name:'Observe',exact:true}).click();await expect(page.getByRole('heading',{name:'Observe from ORAS'})).toBeVisible();await expect(page.locator('.ws-target').first()).toBeVisible({timeout:60000});const old=await page.locator('iframe').elementHandle();
  await page.locator('.ws-target-name').first().click();await expect(page.getByRole('tab',{name:'Selection',exact:true})).toBeVisible({timeout:30000});expect(await old!.evaluate(n=>n.isConnected)).toBe(true);await page.getByRole('button',{name:'Focus',exact:true}).click();
  if(label!=='mobile'){await page.getByRole('button',{name:'Details',exact:true}).click();await expect(page.getByRole('region',{name:'Selected object'})).toHaveClass(/expanded/);await page.keyboard.press('Escape')}else{await page.getByRole('button',{name:'Expand sheet'}).click();await expect(page.locator('.ws-sheet')).toBeVisible();await expect(page.locator('.ws-sheet')).toHaveAttribute('role','region');await expect(page.locator('.ws-sheet')).toHaveCSS('height','640px');expect(await page.locator('iframe').evaluate(n=>(n as HTMLElement).inert)).toBe(false);await page.keyboard.press('Escape')}
  await page.getByRole('button',{name:'Deselect',exact:true}).click();await page.keyboard.press('Escape');await page.keyboard.press('Escape');
  await page.getByRole('tab',{name:'Earth',exact:true}).click();await ready(page,'earth');await layerPanel(page);const aircraft=page.getByRole('switch',{name:'Aircraft near ORAS'});await page.route('**/api/earth/aircraft?*',r=>r.fulfill({status:503,body:'Qualification unavailable'}));await aircraft.click();await expect(page.locator('.ws-layer[data-layer-id=aircraft]')).toContainText('Unavailable',{timeout:20000});await aircraft.click();
  await page.keyboard.press('Escape');await page.keyboard.press('Escape');await page.getByRole('tab',{name:'Sky',exact:true}).click();await ready(page,'sky');expect(await old!.evaluate(n=>n.isConnected)).toBe(false);await page.goBack();await ready(page,'earth');await page.goForward();await ready(page,'sky');await page.reload();await ready(page,'sky');
  expect(await page.evaluate(()=>sessionStorage.getItem('oras.workspace.ui.v1'))).toContain('"pin":true');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
 });
 })
}
test('immersive, auto-hide, keyboard, reduced motion and one-heavy-renderer transitions',async({page})=>{
 test.setTimeout(240000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await ready(page,'sky');await page.locator('iframe').click({position:{x:500,y:300}});await expect(page.locator('.ws-shell')).toHaveAttribute('data-chrome-state','AUTO_HIDDEN',{timeout:10000});await page.getByRole('button',{name:'Show controls'}).click();await page.keyboard.press('Tab');await page.waitForTimeout(4400);await expect(page.locator('.ws-header')).toBeVisible();await page.getByRole('button',{name:'Immersive',exact:true}).click();await expect(page.locator('.ws-stage')).toHaveCSS('top','0px');await page.keyboard.press('Escape');await expect(page.locator('.ws-stage')).toHaveCSS('top','56px');await expect(page.locator('.ws-header')).toBeVisible();await expect(page.locator('.ws-shell')).not.toHaveClass(/ws-shell--(?:immersive|hidden)/);await expect(page.locator('.ws-shell')).not.toHaveAttribute('data-chrome-state','AUTO_HIDDEN');await page.emulateMedia({reducedMotion:'reduce'});expect(await page.locator('.ws-header').evaluate(n=>getComputedStyle(n).transitionDuration)).toContain('0s');
 await pin(page);const frames:any[]=[];for(const mode of ['earth','sky','earth','sky']){frames.push(await page.locator('iframe').elementHandle());await page.getByRole('tab',{name:mode==='sky'?'Sky':'Earth',exact:true}).click();await ready(page,mode);for(const old of frames)expect(await old.evaluate((n:HTMLIFrameElement)=>n.isConnected)).toBe(false)}
 expect(errors).toEqual([])
});
test('immersive Escape recovers Hub, canvas and native controls without stealing native panels',async({page})=>{
 test.setTimeout(120000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/sky-engine');await ready(page,'sky')
 const frame=await (await page.locator('iframe').elementHandle())!.contentFrame()
 for(const focus of ['Hub','canvas','native-control']){
  await page.getByRole('button',{name:'Immersive',exact:true}).click();await expect(page.locator('.ws-stage')).toHaveCSS('top','0px')
  if(focus==='canvas')await frame!.locator('#stel-canvas').click({position:{x:500,y:300}})
  if(focus==='native-control')await frame!.getByRole('button',{name:'Atmosphere',exact:true}).click()
  await page.keyboard.press('Escape');await expect(page.locator('.ws-stage')).toHaveCSS('top','56px')
  // Outlast the exploration timeout: recovery must not be hidden again by its pending timer.
  await page.waitForTimeout(650);await expect(page.locator('.ws-header')).toBeVisible();await expect(page.locator('.ws-shell')).not.toHaveClass(/ws-shell--(?:immersive|hidden)/);await expect(page.locator('.ws-shell')).not.toHaveAttribute('data-chrome-state','AUTO_HIDDEN');await expect(page.locator('iframe')).toHaveCount(1)
 }
 await page.getByRole('button',{name:'Immersive',exact:true}).click();await frame!.getByRole('button',{name:'Sky sources and survey credits',exact:true}).click();await expect(frame!.locator('.v-dialog .text-h5').filter({hasText:'Data Credits'})).toBeVisible();await expect(frame!.locator('.v-dialog--active')).toBeFocused();await page.keyboard.press('Escape');await expect(frame!.locator('.v-dialog .text-h5').filter({hasText:'Data Credits'})).not.toBeVisible();await expect(page.locator('.ws-stage')).toHaveCSS('top','0px');await frame!.locator('#stel-canvas').click({position:{x:500,y:300}});await page.keyboard.press('Escape');await expect(page.locator('.ws-stage')).toHaveCSS('top','56px');expect(errors).toEqual([])
})
test('runtime retry and mismatch preserve product intent',async({page})=>{
 test.setTimeout(120000);await page.route('**/earth-runtime/release.json',r=>r.fulfill({status:503,body:'unavailable'}));await page.goto('/earth');await expect(page.locator('[data-runtime-status=error]')).toBeVisible();await expect(page.locator('iframe')).toHaveCount(0);await page.unroute('**/earth-runtime/release.json');await page.getByRole('button',{name:'Retry Earth',exact:true}).click();await ready(page,'earth');await page.route('**/earth-runtime/release.json',r=>r.fulfill({json:{owner:'wrong',artifact_sha256:'wrong',upstream_sha:'wrong'}}));await page.reload();await expect(page.getByRole('heading',{name:'This view needs an update'})).toBeVisible();await expect(page.locator('iframe')).toHaveCount(0)
});
