import {test,expect} from '@playwright/test'
const pin=()=>sessionStorage.setItem('oras.workspace.ui.v1',JSON.stringify({version:1,pin:true,context:'tonight',layers:['oras-site']}))
const ready=async(page:any)=>expect(page.locator('[data-runtime-status=ready]')).toBeVisible({timeout:90000})
test('Earth Tonight Focus switches to Sky and executes native pointAndLock once',async({page})=>{
 test.setTimeout(120000);await page.addInitScript(pin);await page.addInitScript(()=>{window.addEventListener('oras-sky-ready',()=>{const app=(document.querySelector('#app') as any).__vue__,original=app.$stel.pointAndLock;(window as any).__nativeFocusCalls=0;app.$stel.pointAndLock=function(...args:any[]){(window as any).__nativeFocusCalls++;return original.apply(this,args)}})});await page.goto('/earth');await ready(page);await page.getByRole('button',{name:'Tonight',exact:true}).click();const row=page.locator('.ws-target').first();await expect(row).toBeVisible({timeout:65000});const name=await row.locator('strong').innerText();await row.getByRole('button',{name:'Focus '+name,exact:true}).click();await expect(page).toHaveURL(/\/sky-engine\?/);await ready(page);const sky=page.frames().find(f=>f.url().includes('/oras-sky-engine/'))!;await expect.poll(()=>sky.evaluate(()=>(window as any).__nativeFocusCalls),{timeout:30000}).toBe(1);await page.waitForTimeout(2500);expect(await sky.evaluate(()=>(window as any).__nativeFocusCalls)).toBe(1);await expect(page.getByRole('region',{name:'Selected object',exact:true})).toContainText(name)
})
for(const invalid of ['invalid','2026-02-30T00:00:00Z'])test(`invalid URL date opens Live despite persisted controlled time: ${invalid}`,async({page})=>{
 test.setTimeout(120000);await page.addInitScript(pin);await page.goto('/sky-engine?date=2020-01-01T00%3A00%3A00Z');await ready(page);await page.goto('/sky-engine?date='+encodeURIComponent(invalid));await ready(page);await expect(page.locator('.ws-time .ws-badge')).toHaveText('Live');const sky=page.frames().find(f=>f.url().includes('/oras-sky-engine/'))!;const utc=await sky.evaluate(()=>(document.querySelector('#app') as any).__vue__.$stel.core.observer.utc);expect(Math.abs((utc-40587)*86400000-Date.now())).toBeLessThan(4000)
})
