import {test,expect} from '@playwright/test'
const ready=async(page:any,mode:string)=>expect(page.locator(`[data-runtime-mode=${mode}][data-runtime-status=ready]`)).toBeVisible({timeout:90000})
test('time acknowledgment, keyboard in renderer, focus restoration and contrast',async({page})=>{
 test.setTimeout(120000);await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/?date=2026-10-03T02%3A00%3A00Z');await ready(page,'sky');await page.getByRole('button',{name:'Pin controls',exact:true}).click();const old=await page.locator('iframe').elementHandle();
 await page.getByRole('button',{name:'Change time',exact:true}).click();await page.getByRole('button',{name:'+1h',exact:true}).click();await expect(page).toHaveURL(/date=2026-10-03T03/);expect(await old!.evaluate(n=>n.isConnected)).toBe(true);const skyTime=page.frames().find(f=>f.url().includes('/oras-sky-engine/'))!;await expect.poll(()=>skyTime.evaluate(()=>new Date(Math.round(((document.querySelector('#app') as any).__vue__.$stel.core.observer.utc-40587)*86400000)).toISOString())).toBe('2026-10-03T03:00:00.000Z');await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Change time',exact:true})).toBeFocused();
 const targetSizes=await page.locator('.ws-header button,.ws-header .ws-brand,.ws-time button').evaluateAll(nodes=>nodes.filter(n=>(n as HTMLElement).offsetHeight).map(n=>({name:n.getAttribute('aria-label')||n.textContent,r:n.getBoundingClientRect().toJSON()})));for(const v of targetSizes){expect(v.r.height,v.name||'').toBeGreaterThanOrEqual(44);expect(v.r.width,v.name||'').toBeGreaterThanOrEqual(44)}
 expect(await page.locator('.ws-header').evaluate(n=>getComputedStyle(n).transitionDuration)).toContain('0s');await page.getByRole('button',{name:'Immersive',exact:true}).click();await page.locator('iframe').click({position:{x:500,y:300}});await page.keyboard.press('Escape');await expect(page.locator('.ws-stage')).toHaveCSS('top','56px');await page.locator('iframe').click({position:{x:500,y:300}});await page.keyboard.press('Tab');await expect(page.locator('.ws-brand')).toBeFocused();
 await page.getByRole('button',{name:'Workspace menu',exact:true}).click();await page.getByRole('button',{name:'Sky view settings',exact:true}).click();const sky=page.frameLocator('iframe');await expect(sky.getByText('View settings',{exact:true})).toBeVisible();await expect(sky.getByText('Milky Way',{exact:true})).toBeVisible();await sky.getByRole('button',{name:'Close',exact:true}).click();
 await expect(page.getByRole('main',{name:'Sky workspace'})).toBeVisible();await expect(page.getByRole('banner')).toBeVisible();
 const contrast=await page.locator('.ws-shell').evaluate(n=>{const s=getComputedStyle(n),rgb=(key:string)=>s.getPropertyValue(key).trim();return {text:rgb('--ws-text'),secondary:rgb('--ws-secondary'),muted:rgb('--ws-muted'),surface:rgb('--ws-surface')}});const lum=(hex:string)=>{const c=hex.slice(1).match(/../g)!.map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return c[0]*.2126+c[1]*.7152+c[2]*.0722};for(const text of [contrast.text,contrast.secondary,contrast.muted])expect((lum(text)+.05)/(lum(contrast.surface)+.05)).toBeGreaterThan(4.5)
})
test('mobile gesture snaps, modal focus, source credits and imagery fallback',async({page})=>{
 test.setTimeout(120000);await page.addInitScript(()=>sessionStorage.setItem('oras.workspace.ui.v1',JSON.stringify({version:1,pin:true,context:'tonight',layers:['oras-site','satellites']})));await page.setViewportSize({width:390,height:844});await page.route('https://basemap.nationalmap.gov/**',r=>r.fulfill({status:503,body:'Qualification unavailable'}));await page.route('https://gibs.earthdata.nasa.gov/**',r=>r.fulfill({status:503,body:'Qualification unavailable'}));await page.goto('/earth');await ready(page,'earth');await page.getByRole('button',{name:'Layers',exact:true}).click();await page.getByRole('button',{name:'Return to ORAS',exact:true}).click();await page.getByRole('button',{name:'Close sheet',exact:true}).click();const frame=page.frames().find(f=>f.url().includes('/earth-runtime/'))!;await expect.poll(async()=>String((await frame.evaluate(()=>(window as any).orasEarthDiagnostics())).quality.imagery),{timeout:30000}).toContain('Standard imagery');
 if(await page.getByRole('button',{name:'Show controls'}).isVisible())await page.getByRole('button',{name:'Show controls'}).click();await page.getByRole('button',{name:'Tonight',exact:true}).click();const handle=page.getByRole('button',{name:'Expand sheet',exact:true}),box=await handle.boundingBox();await page.mouse.move(box!.x+22,box!.y+22);await page.mouse.down();await page.mouse.move(box!.x+22,box!.y+122,{steps:4});await page.mouse.up();await expect(page.locator('.ws-sheet')).toHaveClass(/collapsed/);await handle.click();await expect(page.locator('.ws-sheet')).not.toHaveClass(/collapsed/);await handle.click();await expect(page.getByRole('dialog',{name:'Workspace context'})).toBeVisible();expect(await page.locator('iframe').evaluate(n=>(n as HTMLElement).inert)).toBe(true);await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:'Close sheet',exact:true}).click();await expect(page.getByRole('button',{name:'Tonight',exact:true})).toBeFocused();await page.getByRole('button',{name:'Layers',exact:true}).click();await expect(frame.locator('html')).toHaveClass(/credits-top/);const credits=await frame.locator('footer').boundingBox();expect(credits!.y+credits!.height).toBeLessThan(404);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
test('propagated satellite fixture selection, focus, tracking and immediate input cancellation',async({page})=>{
 test.setTimeout(120000);
 const checksum=(line:string)=>{const v=line.padEnd(68,' ');return v+[...v].reduce((sum,c)=>sum+(/\d/.test(c)?Number(c):c==='-'?1:0),0)%10},now=new Date(),day=(now.getTime()-Date.UTC(now.getUTCFullYear(),0,0))/86400000,epoch=String(now.getUTCFullYear()).slice(-2)+day.toFixed(8).padStart(12,'0');
 const fixture=Array.from({length:8},(_,i)=>{const id=String(25544+i);return ['QUALIFICATION FIXTURE '+id,checksum(`1 ${id}U 98067A   ${epoch}  .00016717  00000-0  30122-3 0  999`),checksum(`2 ${id}  51.6434 ${String(i*45).padStart(3,'0')}.0000 0007417  88.2575  28.5079 15.5038153244978`)].join('\n')}).join('\n');await page.route('https://celestrak.org/**',r=>r.fulfill({contentType:'text/plain',body:fixture}));
 await page.addInitScript(()=>sessionStorage.setItem('oras.workspace.ui.v1',JSON.stringify({version:1,pin:true,context:'tonight',layers:['oras-site','satellites']})));await page.goto('/earth?date=2026-10-03T16%3A00%3A00Z');await ready(page,'earth');if(await page.getByRole('button',{name:'Show controls'}).isVisible())await page.getByRole('button',{name:'Show controls'}).click();const frame=page.frames().find(f=>f.url().includes('/earth-runtime/'))!;let target:any;
 for(let attempt=0;attempt<6;attempt++){await page.waitForTimeout(1800);const points=await frame.evaluate(()=>(window as any).orasEarthVisibleTargets());target=points.find((v:any)=>v.kind==='satellites'&&v.x>100&&v.x<1200&&v.y>100&&v.y<650);if(target)break;const canvas=frame.locator('canvas').first();const b=await canvas.boundingBox();await page.mouse.move(b!.x+500,b!.y+300);await page.mouse.down();await page.mouse.move(b!.x+760,b!.y+300,{steps:10});await page.mouse.up()}
 expect(target,'At least one propagated qualification fixture must be visible').toBeTruthy();await frame.locator('canvas').first().click({position:{x:target.x,y:target.y}});await expect(page.getByRole('button',{name:'Track',exact:true})).toBeVisible();await page.getByRole('button',{name:'Focus',exact:true}).click();await page.getByRole('button',{name:'Track',exact:true}).click();await expect.poll(async()=>(await frame.evaluate(()=>(window as any).orasEarthDiagnostics())).tracking).not.toBe(null);await frame.locator('canvas').first().hover({position:{x:500,y:300}});await page.mouse.wheel(0,100);await expect.poll(async()=>(await frame.evaluate(()=>(window as any).orasEarthDiagnostics())).tracking).toBe(null);await page.getByRole('button',{name:'Deselect',exact:true}).click();await expect(page.getByRole('region',{name:'Selected object'})).toHaveCount(0)
})
