import {test,expect} from '@playwright/test'
const pin=()=>sessionStorage.setItem('oras.workspace.ui.v1',JSON.stringify({version:1,pin:true,context:'tonight',layers:['oras-site']}))
const ready=async(page:any)=>expect(page.locator('[data-runtime-status=ready]')).toBeVisible({timeout:90000})
test('runtime fallback retains fixed date and explicit observer intent',async({page})=>{
 test.setTimeout(120000);await page.addInitScript(pin);await page.route('**/oras-sky-engine/oras-runtime-build.json',r=>r.fulfill({status:503,body:'Unavailable'}));await page.goto('/sky-engine?date=2026-10-03T02%3A00%3A00Z&lat=42&lng=-80&elev=0');await expect(page.getByRole('heading',{name:'Sky is unavailable'})).toBeVisible();await page.getByRole('button',{name:'Open Earth',exact:true}).click();await ready(page);const url=new URL(page.url());expect(url.pathname).toBe('/earth');expect(url.searchParams.get('date')).toBe('2026-10-03T02:00:00.000Z');expect(url.searchParams.get('lat')).toBe('42');expect(url.searchParams.get('lng')).toBe('-80');expect(url.searchParams.get('elev')).toBe('0')
})
test('standalone Sky link retains canonical selection observer and fixed scene UTC',async({page})=>{
 test.setTimeout(120000);await page.addInitScript(pin);await page.goto('/sky-engine?date=2026-10-03T02%3A00%3A00Z&lat=42&lng=-80&elev=0');await ready(page);const row=page.locator('.ws-target').first();await expect(row).toBeVisible({timeout:65000});await row.locator('.ws-target-name').click();await expect(page.getByRole('region',{name:'Selected object'})).toBeVisible({timeout:30000});const intent=new URL(page.url()).searchParams;await page.getByRole('button',{name:'Workspace menu',exact:true}).click();const anchor=page.getByRole('link',{name:'Open standalone Sky'}),url=new URL((await anchor.getAttribute('href'))!,page.url());for(const key of ['catalog','source_id','model'])expect(url.searchParams.get(key)).toBe(intent.get(key));expect(Date.parse(url.searchParams.get('date')!)).toBe(Date.parse(intent.get('date')!));for(const key of ['lat','lng','elev'])expect(Number(url.searchParams.get(key))).toBeCloseTo(Number(intent.get(key)),6);const popupPromise=page.waitForEvent('popup');await anchor.click();const popup=await popupPromise;await expect.poll(()=>popup.evaluate(()=>(document.querySelector('#app') as any)?.__vue__?.$store?.state?.selectedObject?.source_id),{timeout:45000}).toBe(intent.get('source_id'));await popup.close()
})
for(const width of [1440,390])test(`Escape from a focused More action restores its stable trigger ${width}`,async({page})=>{
 test.setTimeout(120000);await page.setViewportSize({width,height:width===390?844:900});await page.addInitScript(pin);await page.goto('/earth');await ready(page);const trigger=page.getByRole('button',{name:'Workspace menu',exact:true});await trigger.click();await page.locator('.ws-menu').getByRole('button',{name:'Controls pinned',exact:true}).click();await page.keyboard.press('Escape');await expect(page.locator('.ws-menu')).toHaveCount(0);await expect(trigger).toBeFocused()
})
