import {test,expect} from '@playwright/test'
import {currentObservingNight} from '../../src/features/tonight/nightClock'
const pin=()=>sessionStorage.setItem('oras.workspace.ui.v1',JSON.stringify({version:1,pin:true,context:'tonight',layers:['oras-site','satellites']}))
const ready=async(page:any)=>expect(page.locator('[data-runtime-status=ready]')).toBeVisible({timeout:90000})
for(const source of ['','?date=2026-10-03T02%3A00%3A00Z'])test(`Tonight peak Focus preserves its acknowledged UTC and canonical identity ${source||'Live'}`,async({page})=>{
 test.setTimeout(120000);await page.addInitScript(pin);const requested=new URLSearchParams(source).get('date'),night=currentObservingNight(requested?new Date(requested):new Date());const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/tonight'&&new URL(r.url()).searchParams.get('date')===night&&r.ok(),{timeout:65000});await page.goto('/'+source);const payload=await(await response).json();await ready(page);await page.getByRole('button',{name:'Tonight',exact:true}).click();const row=page.locator('.ws-target').first();await expect(row).toBeVisible({timeout:65000});const name=await row.locator('strong').innerText(),target=payload.data.targets.find((v:any)=>v.name===name),link=new URL(target.sky_engine_url,page.url());expect(link.searchParams.get('date')).toBeTruthy();const peakUtc=new Date(link.searchParams.get('date')!).toISOString();const old=await page.locator('iframe').elementHandle();await row.getByRole('button',{name:'Focus '+name,exact:true}).click();await expect.poll(()=>new URL(page.url()).searchParams.get('date'),{timeout:30000}).toBe(peakUtc);await page.waitForTimeout(5000);expect(new URL(page.url()).searchParams.get('date')).toBe(peakUtc);expect(new URL(page.url()).searchParams.get('source_id')).toBe(link.searchParams.get('source_id'));expect(await old!.evaluate(n=>n.isConnected)).toBe(true);const sky=page.frames().find(f=>f.url().includes('/oras-sky-engine/'))!;const effective=await sky.evaluate(()=>(document.querySelector('#app') as any).__vue__.$stel.core.observer.utc);const expected=Date.parse(link.searchParams.get('date')!)/86400000+40587;expect(Math.abs(effective-expected)*86400000).toBeLessThan(1000)
})
test('custom observer survives focused Observe with UTC presentation',async({page})=>{
 test.setTimeout(120000);await page.addInitScript(pin);await page.goto('/sky-engine?lat=42&lng=-80&elev=365.76&date=2026-10-03T02%3A00%3A00Z');await ready(page);await page.getByRole('button',{name:'Observe',exact:true}).click();await expect(page.locator('.ws-target').first()).toBeVisible({timeout:65000});await expect(page.locator('.ws-context .ws-meta').first()).toContainText('UTC');const link=page.getByRole('link',{name:'Open focused Observe',exact:true}),href=new URL((await link.getAttribute('href'))!,page.url());expect(href.searchParams.get('lat')).toBe('42');expect(href.searchParams.get('lon')).toBe('-80');expect(Number(href.searchParams.get('elevation_ft'))).toBeCloseTo(1200,5);expect(href.searchParams.get('at')).toBe('2026-10-03T02:00:00.000Z');await link.click();await expect(page.getByRole('heading',{name:'Observe this sky'})).toBeVisible();await expect(page.locator('.observe-context-time')).toContainText('UTC')
})
for(const width of [1440,390])test(`menu Diagnostics returns focus to stable menu trigger ${width}`,async({page})=>{
 test.setTimeout(120000);await page.setViewportSize({width,height:width===390?844:900});await page.addInitScript(pin);await page.goto('/earth');await ready(page);const trigger=page.getByRole('button',{name:'Workspace menu',exact:true});await trigger.click();await page.getByRole('button',{name:'Diagnostics',exact:true}).click();if(width===390)await page.getByRole('button',{name:'Close sheet',exact:true}).click();else await page.getByRole('button',{name:'Close panel',exact:true}).click();await expect(trigger).toBeFocused();await page.waitForTimeout(4500);await expect(trigger).toBeVisible()
})
test('Sky rejects a stale application digest before mounting renderer',async({page})=>{
 await page.route('**/oras-sky-engine/oras-runtime-build.json',async r=>{const response=await r.fetch();const marker=await response.json();await r.fulfill({json:{...marker,artifact_sha256:'stale'}})});await page.goto('/');await expect(page.getByRole('heading',{name:'This view needs an update',exact:true})).toBeVisible();await expect(page.locator('iframe')).toHaveCount(0)
})
