import {test,expect} from '@playwright/test'
test.use({timezoneId:'Asia/Tokyo'})
test('Earth refreshes enabled observer sources in-place before B acknowledgement; custom times stay UTC',async({page})=>{
 test.setTimeout(120000)
 await page.addInitScript(()=>{sessionStorage.setItem('oras.workspace.ui.v1',JSON.stringify({version:1,pin:true,context:'tonight',layers:['oras-site','aircraft','weather']}));const original=MessagePort.prototype.postMessage;MessagePort.prototype.postMessage=function(data:any,...rest:any[]){if(data?.type==='result'&&data.command==='setObserverIntent')(window as any).observerAcks=((window as any).observerAcks||[]).concat(data.payload);return original.call(this,data,...rest as [])}})
 let release:()=>void=()=>{};const gate=new Promise<void>(resolve=>release=resolve),requests:string[]=[]
 await page.route('**/api/earth/aircraft?*',async route=>{const url=new URL(route.request().url());requests.push('aircraft:'+url.searchParams.get('lat'));if(url.searchParams.get('lat')==='35')await gate;await route.fulfill({json:{now:Date.now(),ac:[{hex:'abc123',flight:'QUALIFICATION',lat:Number(url.searchParams.get('lat')),lon:Number(url.searchParams.get('lon')),alt_geom:10000,seen:0,seen_pos:0}]}}).catch(()=>{})})
 await page.route('https://api.open-meteo.com/**',async route=>{const url=new URL(route.request().url());requests.push('weather:'+url.searchParams.get('latitude'));if(url.searchParams.get('latitude')==='35'){await gate;await route.fulfill({status:503,json:{error:true}}).catch(()=>{});return}await route.fulfill({json:{current:{temperature_2m:12,cloud_cover:50,weather_code:3,time:new Date().toISOString().slice(0,16)}}})})
 await page.goto('/earth?lat=42&lng=-80&elev=0&date=2026-10-03T02%3A00%3A00Z');await expect(page.locator('[data-runtime-status=ready]')).toBeVisible({timeout:90000})
 const earth=page.frames().find(f=>f.url().includes('/earth-runtime/'))!,frame=await page.locator('iframe').elementHandle()
 const provider=(id:string)=>earth.locator(`[data-layer-id=${id}] [data-provider-status]`)
 await expect(provider('aircraft')).toHaveAttribute('data-provider-status','ready',{timeout:30000});await expect(provider('weather')).toHaveAttribute('data-provider-status','ready',{timeout:30000})
 await earth.evaluate(()=>{(window as any).observerAcks=[]})
 await page.evaluate(()=>{history.pushState(null,'','/earth?lat=35&lng=-120&elev=0&date=2026-10-03T02%3A00%3A00Z');dispatchEvent(new PopStateEvent('popstate'))})
 await expect.poll(()=>requests.includes('aircraft:35')&&requests.includes('weather:35')).toBe(true)
 await expect(provider('aircraft')).toHaveAttribute('data-provider-status','loading');await expect(provider('weather')).toHaveAttribute('data-provider-status','loading')
 expect(await earth.evaluate(()=>(window as any).observerAcks)).toEqual([])
 expect(await earth.evaluate(()=>(window as any).orasEarthVisibleTargets().filter((target:any)=>['aircraft','weather'].includes(target.kind)))).toEqual([])
 expect(await earth.evaluate(()=>(window as any).orasEarthDiagnostics().site)).toEqual({lat:41.321903,lon:-79.585394,elevationM:432.816})
 expect(await frame!.evaluate(n=>n.isConnected)).toBe(true)
 release();await expect(provider('aircraft')).toHaveAttribute('data-provider-status','ready');await expect(provider('weather')).toHaveAttribute('data-provider-status','unavailable')
 await expect.poll(()=>earth.evaluate(()=>(window as any).observerAcks)).toEqual([{ok:true,effectiveObserver:{lat:35,lon:-120,elevationM:0}}])
 expect(await frame!.evaluate(n=>n.isConnected)).toBe(true)
 await page.getByRole('button',{name:'Time details',exact:true}).click();const details=page.getByRole('region',{name:'Time details'});await expect(details).toContainText('Requested scene time: Oct 3, 2:00 AM UTC');await expect(details).toContainText('Effective scene time: Oct 3, 2:00 AM UTC');await page.screenshot({path:'../output/playwright/unified-workspace/time-observer.png'})
})
