import {test,expect} from '@playwright/test'
const pin=()=>sessionStorage.setItem('oras.workspace.ui.v1',JSON.stringify({version:1,pin:true,context:'tonight',layers:['oras-site']}))
const ready=async(page:any)=>expect(page.locator('[data-runtime-status=ready]')).toBeVisible({timeout:90000})
test('Earth Tonight Focus switches to Sky and executes native pointAndLock once',async({page})=>{
 test.setTimeout(120000);await page.addInitScript(pin);await page.addInitScript(()=>{window.addEventListener('oras-sky-ready',()=>{const app=(document.querySelector('#app') as any).__vue__,original=app.$stel.pointAndLock;(window as any).__nativeFocusCalls=0;app.$stel.pointAndLock=function(...args:any[]){(window as any).__nativeFocusCalls++;return original.apply(this,args)}})});await page.goto('/earth');await ready(page);await page.getByRole('button',{name:'Tonight',exact:true}).click();const row=page.locator('.ws-target').first();await expect(row).toBeVisible({timeout:65000});const name=await row.locator('strong').innerText();await row.getByRole('button',{name:'Focus '+name,exact:true}).click();await expect(page).toHaveURL(/\/sky-engine\?/);await ready(page);const sky=page.frames().find(f=>f.url().includes('/oras-sky-engine/'))!;await expect.poll(()=>sky.evaluate(()=>(window as any).__nativeFocusCalls),{timeout:30000}).toBe(1);await page.waitForTimeout(2500);expect(await sky.evaluate(()=>(window as any).__nativeFocusCalls)).toBe(1);await expect(page.getByRole('region',{name:'Selected object',exact:true})).toContainText(name)
})
for(const invalid of ['invalid','2026-02-30T00:00:00Z'])test(`invalid URL date opens Live despite persisted controlled time: ${invalid}`,async({page})=>{
 test.setTimeout(120000);await page.addInitScript(pin);await page.goto('/sky-engine?date=2020-01-01T00%3A00%3A00Z');await ready(page);await page.goto('/sky-engine?date='+encodeURIComponent(invalid));await ready(page);await expect(page.locator('.ws-time .ws-badge')).toHaveText('Live');const sky=page.frames().find(f=>f.url().includes('/oras-sky-engine/'))!;const utc=await sky.evaluate(()=>(document.querySelector('#app') as any).__vue__.$stel.core.observer.utc);expect(Math.abs((utc-40587)*86400000-Date.now())).toBeLessThan(4000)
})
test('explicit observer coordinates without elevation retain the native zero-height contract',async({page})=>{
 test.setTimeout(120000);await page.addInitScript(pin);await page.goto('/sky-engine?lat=42&lng=-80&date=2026-10-03T02%3A00%3A00Z');await ready(page);const sky=page.frames().find(f=>f.url().includes('/oras-sky-engine/'))!;const observer=await sky.evaluate(()=>{const v=(document.querySelector('#app') as any).__vue__.$stel.core.observer;return {lat:v.latitude*180/Math.PI,lon:v.longitude*180/Math.PI,elev:v.elevation}});expect(observer.lat).toBeCloseTo(42,6);expect(observer.lon).toBeCloseTo(-80,6);expect(observer.elev).toBe(0);await page.getByRole('button',{name:'Observe',exact:true}).click();await expect(page.getByRole('link',{name:'Open focused Observe'})).toHaveAttribute('href',/lat=42&lon=-80&elevation_ft=0/)
})
for(const width of [1440,390])test(`closing auxiliary time restores the prior Tonight context ${width}`,async({page})=>{
 test.setTimeout(120000);await page.setViewportSize({width,height:width===390?844:900});await page.addInitScript(pin);await page.goto('/');await ready(page);if(width===390){await page.getByRole('button',{name:'Tonight',exact:true}).click();await page.locator('.ws-sheet').getByRole('button',{name:'Time',exact:true}).click()}else await page.getByRole('button',{name:'Change time',exact:true}).click();await expect(page.locator('#ws-date')).toBeVisible();if(width===390)await page.getByRole('button',{name:'Close sheet',exact:true}).click();else await page.getByRole('button',{name:'Close panel',exact:true}).click();await expect(page.getByRole('heading',{name:'Tonight at ORAS'})).toBeVisible();await expect(page.locator('#ws-date')).toHaveCount(0);if(width===390)await expect(page.locator('.ws-sheet').getByRole('button',{name:'Time',exact:true})).toBeFocused()
})
test('Escape still dismisses selected context outside an auxiliary surface',async({page})=>{
 test.setTimeout(120000);await page.addInitScript(pin);await page.goto('/');await ready(page);const row=page.locator('.ws-target').first();await expect(row).toBeVisible({timeout:65000});await row.locator('.ws-target-name').click();await expect(page.getByRole('region',{name:'Selected object'})).toBeVisible({timeout:30000});await page.locator('.ws-context').getByRole('button',{name:'Close panel',exact:true}).focus();await page.keyboard.press('Escape');await expect(page.locator('.ws-context')).toHaveCount(0)
})
