import {test,expect} from '@playwright/test'
const pin=()=>sessionStorage.setItem('oras.workspace.ui.v1',JSON.stringify({version:1,pin:true,context:'tonight',layers:['oras-site','satellites']}))
const ready=async(page:any)=>expect(page.locator('[data-runtime-status=ready]')).toBeVisible({timeout:90000})
test('time editor reflects plus one hour and Apply retains the new effective UTC',async({page})=>{
 test.setTimeout(120000);await page.addInitScript(pin);await page.goto('/?date=2026-10-03T02%3A00%3A00Z');await ready(page);await page.getByRole('button',{name:'Change time',exact:true}).click();const input=page.locator('#ws-date'),old=await input.inputValue();await page.getByRole('button',{name:'+1h',exact:true}).click();await expect.poll(()=>input.inputValue()).not.toBe(old);await page.getByRole('button',{name:'Apply',exact:true}).click();await expect.poll(()=>new URL(page.url()).searchParams.get('date')).toBe('2026-10-03T03:00:00.000Z');await page.waitForTimeout(2000);expect(new URL(page.url()).searchParams.get('date')).toBe('2026-10-03T03:00:00.000Z')
})
test('Tonight uses the acknowledged selected observing night',async({page})=>{
 test.setTimeout(120000);await page.addInitScript(pin);const requests:string[]=[];page.on('request',r=>{const url=new URL(r.url());if(url.pathname==='/api/tonight')requests.push(url.searchParams.get('date')!)});await page.goto('/?date=2026-10-01T02%3A00%3A00Z');await ready(page);await expect.poll(()=>requests).toContain('2026-09-30');await expect(page.locator('.ws-context .ws-eyebrow').first()).toContainText('2026-09-30',{timeout:65000});await expect(page.getByRole('link',{name:'Full night plan'})).toHaveAttribute('href','/tonight?date=2026-09-30')
})
for(const width of [1440,390])test(`Immersive from More keeps chrome hidden ${width}`,async({page})=>{
 test.setTimeout(120000);await page.setViewportSize({width,height:width===390?844:900});await page.addInitScript(pin);await page.goto('/earth');await ready(page);await page.getByRole('button',{name:'Workspace menu',exact:true}).click();await page.locator('.ws-menu').getByRole('button',{name:'Immersive',exact:true}).click();await expect(page.locator('.ws-stage')).toHaveCSS('top','0px');await expect(page.locator('.ws-header')).not.toBeVisible();await page.waitForTimeout(1000);await expect(page.locator('.ws-header')).not.toBeVisible();await expect(page.getByRole('button',{name:'Show controls'})).toBeVisible()
})
test('tilted Earth keyboard and wheel zoom retain the admitted altitude bounds',async({page})=>{
 test.setTimeout(120000);await page.addInitScript(pin);await page.goto('/earth');await ready(page);await page.getByRole('button',{name:'Return to ORAS',exact:true}).click();await page.waitForTimeout(1200);const earth=page.frames().find(f=>f.url().includes('/earth-runtime/'))!,canvas=earth.locator('canvas').first();await canvas.click({position:{x:500,y:300}});await canvas.evaluate(n=>{for(let i=0;i<120;i++)n.dispatchEvent(new KeyboardEvent('keydown',{key:'+',bubbles:true}))});let height=await earth.evaluate(()=>(window as any).orasEarthDiagnostics().cameraHeightM);expect(height).toBeGreaterThanOrEqual(99.99);expect(height).toBeLessThan(101);await canvas.evaluate(n=>{for(let i=0;i<150;i++)n.dispatchEvent(new WheelEvent('wheel',{deltaY:100,bubbles:true,cancelable:true}))});height=await earth.evaluate(()=>(window as any).orasEarthDiagnostics().cameraHeightM);expect(height).toBeLessThanOrEqual(30000001);expect(height).toBeGreaterThan(29999999);await expect(page.locator('[data-runtime-status=ready]')).toBeVisible()
})
