import {test,expect} from '@playwright/test'
const pin=()=>sessionStorage.setItem('oras.workspace.ui.v1',JSON.stringify({version:1,pin:true,context:'tonight',layers:['oras-site']}))
const ready=async(page:any)=>expect(page.locator('[data-runtime-status=ready]')).toBeVisible({timeout:90000})
test('in-place exact query changes restore native observer selection and explicit clearing',async({page})=>{
 test.setTimeout(120000);await page.addInitScript(pin);const payload=await(await page.request.get('/api/tonight?date=2026-10-02')).json(),targets=payload.data.top_opportunities.slice(0,2).map((id:any)=>payload.data.targets.find((t:any)=>t.catalog===id.catalog&&t.source_id===id.source_id&&t.model===id.model));const path=(target:any,lat:number,lon:number)=>{const p=new URL(target.sky_engine_url,'http://oras.test').searchParams;p.set('date','2026-10-03T02:00:00.000Z');p.set('lat',String(lat));p.set('lng',String(lon));p.set('elev','0');return '/sky-engine?'+p};await page.goto(path(targets[0],42,-80));await ready(page);const old=await page.locator('iframe').elementHandle(),sky=page.frames().find(f=>f.url().includes('/oras-sky-engine/'))!;await expect.poll(()=>sky.evaluate(()=>(document.querySelector('#app') as any).__vue__.$store.state.selectedObject?.source_id),{timeout:30000}).toBe(targets[0].source_id);await page.evaluate(url=>{history.pushState(null,'',url);dispatchEvent(new PopStateEvent('popstate'))},path(targets[1],35,-120));await expect.poll(()=>sky.evaluate(()=>(document.querySelector('#app') as any).__vue__.$store.state.selectedObject?.source_id),{timeout:30000}).toBe(targets[1].source_id);const observer=await sky.evaluate(()=>{const v=(document.querySelector('#app') as any).__vue__.$stel.core.observer;return {lat:v.latitude*180/Math.PI,lon:v.longitude*180/Math.PI}});expect(observer.lat).toBeCloseTo(35,6);expect(observer.lon).toBeCloseTo(-120,6);expect(await old!.evaluate(n=>n.isConnected)).toBe(true);await page.evaluate(()=>{history.pushState(null,'','/sky-engine?date=2026-10-03T02%3A00%3A00.000Z&lat=35&lng=-120&elev=0');dispatchEvent(new PopStateEvent('popstate'))});await expect(page.getByRole('region',{name:'Selected object'})).toHaveCount(0);expect(await old!.evaluate(n=>n.isConnected)).toBe(true)
})
test('empty Earth canvas click retains selection until explicit Deselect',async({page})=>{
 test.setTimeout(120000);await page.addInitScript(pin);await page.goto('/earth');await ready(page);await page.getByRole('button',{name:'Return to ORAS',exact:true}).click();await page.waitForTimeout(1200);const earth=page.frames().find(f=>f.url().includes('/earth-runtime/'))!,canvas=earth.locator('canvas').first(),box=await canvas.boundingBox();await canvas.click({position:{x:box!.width/2,y:box!.height/2}});await expect(page.getByRole('region',{name:'Selected object'})).toContainText('Oil Region');await canvas.click({position:{x:450,y:100}});await expect(page.getByRole('region',{name:'Selected object'})).toContainText('Oil Region');await page.getByRole('button',{name:'Deselect',exact:true}).click();await expect(page.getByRole('region',{name:'Selected object'})).toHaveCount(0)
})
test('custom Earth source timestamps use explicit UTC with a declared weather fixture',async({page})=>{
 test.setTimeout(120000);await page.addInitScript(()=>sessionStorage.setItem('oras.workspace.ui.v1',JSON.stringify({version:1,pin:true,context:'tonight',layers:['oras-site','weather']})));await page.route('https://api.open-meteo.com/**',r=>r.fulfill({json:{current:{temperature_2m:12,cloud_cover:50,weather_code:3,time:new Date().toISOString().slice(0,16)}}}));await page.goto('/earth?lat=42&lng=-80&elev=0');await ready(page);await page.getByRole('button',{name:'Layers',exact:true}).click();await expect(page.locator('[data-layer-id=weather] time')).toContainText('UTC',{timeout:30000})
})
