import type { SkyEngineCelestialSourceObject } from './types'

export const SKY_ENGINE_SCENE_TIMESTAMP = '2026-07-15T02:00:00.000Z'

export const SKY_ENGINE_REAL_SKY_STARTERS: readonly SkyEngineCelestialSourceObject[] = [
  {
    id: 'sky-real-vega',
    name: 'Vega',
    type: 'star',
    rightAscensionHours: 18.615649,
    declinationDeg: 38.783689,
    magnitude: 0.03,
    colorHex: '#8ec5ff',
    summary: 'Bright Lyra star positioned from catalog right ascension and declination.',
    description: 'Vega is computed for the fixed ORAS observer and explicit scene timestamp used by this slice.',
    constellation: 'Lyra',
  },
  {
    id: 'sky-real-deneb',
    name: 'Deneb',
    type: 'star',
    rightAscensionHours: 20.690532,
    declinationDeg: 45.280339,
    magnitude: 1.25,
    colorHex: '#d6e7ff',
    summary: 'Cygnus anchor star computed into the live Babylon sky viewport.',
    description: 'Deneb remains a selectable object, but its on-screen placement now comes from real sky math instead of seeded placement.',
    constellation: 'Cygnus',
  },
  {
    id: 'sky-real-altair',
    name: 'Altair',
    type: 'star',
    rightAscensionHours: 19.846389,
    declinationDeg: 8.868321,
    magnitude: 0.77,
    colorHex: '#f4fbff',
    summary: 'Aquila star computed from celestial coordinates for the current scene context.',
    description: 'Altair helps prove that multiple fixed stars move consistently when the scene timestamp changes.',
    constellation: 'Aquila',
  },
  {
    id: 'sky-real-polaris',
    name: 'Polaris',
    type: 'star',
    rightAscensionHours: 2.530301,
    declinationDeg: 89.26411,
    magnitude: 1.98,
    colorHex: '#fff2d6',
    summary: 'North Star reference computed from its catalog coordinates.',
    description: 'Polaris provides a stable, above-horizon reference point near the north celestial pole.',
    constellation: 'Ursa Minor',
  },
  {
    id: 'sky-real-arcturus',
    name: 'Arcturus',
    type: 'star',
    rightAscensionHours: 14.261021,
    declinationDeg: 19.18241,
    magnitude: -0.05,
    colorHex: '#ffcb95',
    summary: 'Bright Bootes star added as a fifth computed starter object.',
    description: 'Arcturus is included to keep the starter set above the minimum three-object requirement while remaining tightly scoped.',
    constellation: 'Bootes',
  },
  {
    id: 'sky-real-albireo',
    name: 'Albireo',
    type: 'star',
    rightAscensionHours: 19.512028,
    declinationDeg: 27.959681,
    magnitude: 3.05,
    colorHex: '#ffd9a1',
    summary: 'Cygnus anchor star used to give the observer a readable constellation stem.',
    description: 'Albireo extends the starter set enough to support a useful constellation overlay without turning the scene into a dense catalog dump.',
    constellation: 'Cygnus',
  },
  {
    id: 'sky-real-tarazed',
    name: 'Tarazed',
    type: 'star',
    rightAscensionHours: 19.770994,
    declinationDeg: 10.613268,
    magnitude: 2.72,
    colorHex: '#ffc28f',
    summary: 'Aquila companion star that helps ground Altair in a recognisable shape.',
    description: 'Tarazed stays bright enough to support observer guidance while remaining light enough for the label solver to suppress when the view is crowded.',
    constellation: 'Aquila',
  },
  {
    id: 'sky-real-sheliak',
    name: 'Sheliak',
    type: 'star',
    rightAscensionHours: 18.834665,
    declinationDeg: 33.362667,
    magnitude: 3.45,
    colorHex: '#d4e2ff',
    summary: 'Lyra support star used for a subtle constellation trace near Vega.',
    description: 'Sheliak gives the scene one more real-sky reference for the aid layer while staying far below the label priority of the brightest stars.',
    constellation: 'Lyra',
  },
  {
    id: 'sky-real-sulafat',
    name: 'Sulafat',
    type: 'star',
    rightAscensionHours: 18.982396,
    declinationDeg: 32.689557,
    magnitude: 3.25,
    colorHex: '#cadbff',
    summary: 'Second Lyra anchor used to draw a compact, readable aid cluster.',
    description: 'Sulafat expands the starter set just enough to support constellation and guidance overlays without pushing into catalog-scale complexity.',
    constellation: 'Lyra',
  },
] as const