from copy import deepcopy


TIER1_BRIGHT_STAR_TILE_ID = "tier1-bright-stars"
TIER1_BRIGHT_STAR_LOOKUP_KEY = "sky:tier1:tier1-bright-stars"
TIER1_BRIGHT_STAR_SOURCE = "bright_star_catalog"


BRIGHT_STAR_SCENE_OBJECTS = [
    {
        "id": "star-sirius",
        "type": "star",
        "name": "Sirius",
        "engine": "sky_engine",
        "right_ascension": 6.7525,
        "declination": -16.7161,
        "magnitude": -1.46,
        "color_index": 0.0,
    },
    {
        "id": "star-canopus",
        "type": "star",
        "name": "Canopus",
        "engine": "sky_engine",
        "right_ascension": 6.3992,
        "declination": -52.6957,
        "magnitude": -0.74,
        "color_index": 0.15,
    },
    {
        "id": "star-alpha-centauri",
        "type": "star",
        "name": "Alpha Centauri",
        "engine": "sky_engine",
        "right_ascension": 14.6601,
        "declination": -60.8339,
        "magnitude": -0.27,
        "color_index": 0.71,
    },
    {
        "id": "star-arcturus",
        "type": "star",
        "name": "Arcturus",
        "engine": "sky_engine",
        "right_ascension": 14.261,
        "declination": 19.1824,
        "magnitude": -0.05,
        "color_index": 1.23,
    },
    {
        "id": "star-vega",
        "type": "star",
        "name": "Vega",
        "engine": "sky_engine",
        "right_ascension": 18.6156,
        "declination": 38.7837,
        "magnitude": 0.03,
        "color_index": 0.0,
    },
    {
        "id": "star-capella",
        "type": "star",
        "name": "Capella",
        "engine": "sky_engine",
        "right_ascension": 5.2782,
        "declination": 45.998,
        "magnitude": 0.08,
        "color_index": 0.8,
    },
    {
        "id": "star-rigel",
        "type": "star",
        "name": "Rigel",
        "engine": "sky_engine",
        "right_ascension": 5.2423,
        "declination": -8.2016,
        "magnitude": 0.13,
        "color_index": -0.03,
    },
    {
        "id": "star-procyon",
        "type": "star",
        "name": "Procyon",
        "engine": "sky_engine",
        "right_ascension": 7.655,
        "declination": 5.225,
        "magnitude": 0.34,
        "color_index": 0.42,
    },
    {
        "id": "star-achernar",
        "type": "star",
        "name": "Achernar",
        "engine": "sky_engine",
        "right_ascension": 1.6286,
        "declination": -57.2368,
        "magnitude": 0.46,
        "color_index": -0.16,
    },
    {
        "id": "star-betelgeuse",
        "type": "star",
        "name": "Betelgeuse",
        "engine": "sky_engine",
        "right_ascension": 5.9195,
        "declination": 7.4071,
        "magnitude": 0.5,
        "color_index": 1.85,
    },
    {
        "id": "star-hadar",
        "type": "star",
        "name": "Hadar",
        "engine": "sky_engine",
        "right_ascension": 14.0637,
        "declination": -60.373,
        "magnitude": 0.61,
        "color_index": -0.23,
    },
    {
        "id": "star-altair",
        "type": "star",
        "name": "Altair",
        "engine": "sky_engine",
        "right_ascension": 19.8464,
        "declination": 8.8683,
        "magnitude": 0.77,
        "color_index": 0.22,
    },
    {
        "id": "star-acrux",
        "type": "star",
        "name": "Acrux",
        "engine": "sky_engine",
        "right_ascension": 12.4433,
        "declination": -63.0991,
        "magnitude": 0.76,
        "color_index": -0.24,
    },
    {
        "id": "star-aldebaran",
        "type": "star",
        "name": "Aldebaran",
        "engine": "sky_engine",
        "right_ascension": 4.5987,
        "declination": 16.5093,
        "magnitude": 0.86,
        "color_index": 1.54,
    },
    {
        "id": "star-antares",
        "type": "star",
        "name": "Antares",
        "engine": "sky_engine",
        "right_ascension": 16.4901,
        "declination": -26.4319,
        "magnitude": 0.96,
        "color_index": 1.83,
    },
    {
        "id": "star-spica",
        "type": "star",
        "name": "Spica",
        "engine": "sky_engine",
        "right_ascension": 13.4199,
        "declination": -11.1614,
        "magnitude": 0.98,
        "color_index": -0.23,
    },
    {
        "id": "star-pollux",
        "type": "star",
        "name": "Pollux",
        "engine": "sky_engine",
        "right_ascension": 7.7553,
        "declination": 28.0262,
        "magnitude": 1.14,
        "color_index": 1.0,
    },
    {
        "id": "star-fomalhaut",
        "type": "star",
        "name": "Fomalhaut",
        "engine": "sky_engine",
        "right_ascension": 22.9608,
        "declination": -29.6222,
        "magnitude": 1.16,
        "color_index": 0.09,
    },
    {
        "id": "star-deneb",
        "type": "star",
        "name": "Deneb",
        "engine": "sky_engine",
        "right_ascension": 20.6905,
        "declination": 45.2803,
        "magnitude": 1.25,
        "color_index": 0.09,
    },
    {
        "id": "star-mimosa",
        "type": "star",
        "name": "Mimosa",
        "engine": "sky_engine",
        "right_ascension": 12.7953,
        "declination": -59.6888,
        "magnitude": 1.25,
        "color_index": -0.23,
    },
    {
        "id": "star-regulus",
        "type": "star",
        "name": "Regulus",
        "engine": "sky_engine",
        "right_ascension": 10.1395,
        "declination": 11.9672,
        "magnitude": 1.35,
        "color_index": -0.11,
    },
    {
        "id": "star-adhara",
        "type": "star",
        "name": "Adhara",
        "engine": "sky_engine",
        "right_ascension": 6.9771,
        "declination": -28.9721,
        "magnitude": 1.5,
        "color_index": -0.24,
    },
    {
        "id": "star-shaula",
        "type": "star",
        "name": "Shaula",
        "engine": "sky_engine",
        "right_ascension": 17.5601,
        "declination": -37.1038,
        "magnitude": 1.62,
        "color_index": -0.23,
    },
    {
        "id": "star-castor",
        "type": "star",
        "name": "Castor",
        "engine": "sky_engine",
        "right_ascension": 7.5767,
        "declination": 31.8883,
        "magnitude": 1.58,
        "color_index": 0.0,
    },
]


def build_bright_star_scene_objects() -> list[dict]:
    return [deepcopy(star) for star in BRIGHT_STAR_SCENE_OBJECTS]


def build_tier1_bright_star_tile_descriptor() -> dict:
    magnitudes = [float(star["magnitude"]) for star in BRIGHT_STAR_SCENE_OBJECTS]
    return {
        "tier": 1,
        "tile_id": TIER1_BRIGHT_STAR_TILE_ID,
        "lookup_key": TIER1_BRIGHT_STAR_LOOKUP_KEY,
        "source": TIER1_BRIGHT_STAR_SOURCE,
        "object_count": len(BRIGHT_STAR_SCENE_OBJECTS),
        "magnitude_min": min(magnitudes),
        "magnitude_max": max(magnitudes),
    }