/**
 * Downloads Stellarium Web Engine `src/hip.inl` at the pinned commit and emits
 * `hipPixOrder2.generated.ts` (base64 table + length) for `hipGetPix.ts`.
 *
 * Source of truth: docs/runtime/port/stellarium-web-engine-src.md
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const PINNED =
  'https://raw.githubusercontent.com/Stellarium/stellarium-web-engine/63fb3279e85782158a6df63649f1c8a1837b7846/src/hip.inl'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outPath = join(
  __dirname,
  '..',
  'src',
  'features',
  'sky-engine',
  'engine',
  'sky',
  'adapters',
  'hipPixOrder2.generated.ts',
)

const res = await fetch(PINNED)
if (!res.ok) {
  throw new Error(`Failed to fetch ${PINNED}: ${res.status}`)
}

const text = await res.text()
const stripped = text.replace(/\/\/[^\n]*/g, '')
const nums = stripped.match(/\d+/g)
if (!nums) {
  throw new Error('hip.inl: no numeric entries')
}

const bytes = Uint8Array.from(nums.map((s) => {
  const v = Number(s)
  if (!Number.isInteger(v) || v < 0 || v > 255) {
    throw new Error(`hip.inl: out-of-range byte ${s}`)
  }
  return v
}))

const b64 = Buffer.from(bytes).toString('base64')

const ts = `/* eslint-disable max-len */
/**
 * AUTO-GENERATED by scripts/generate_hip_pix_order2.mjs — do not edit by hand.
 * Stellarium Web Engine \`src/hip.inl\` (HIP → nested HEALPix pixel at order 2).
 * Pinned revision: 63fb3279e85782158a6df63649f1c8a1837b7846
 */
export const HIP_PIX_ORDER_2_BYTE_LENGTH = ${bytes.length} as const

/** Base64-encoded \`PIX_ORDER_2\` bytes (same order as Stellarium \`hip.c\`). */
export const HIP_PIX_ORDER_2_BASE64 = ${JSON.stringify(b64)}
`

writeFileSync(outPath, ts, 'utf8')
console.log(`Wrote ${bytes.length} bytes → ${outPath}`)
