#!/usr/bin/env node
import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { execFile as execFileCb } from 'node:child_process'
import { promisify } from 'node:util'

const execFile = promisify(execFileCb)

const PINNED_SOURCE_REVISION = '63fb3279e85782158a6df63649f1c8a1837b7846'

const BV_PROBES = [-0.2, 0, 0.58, 1.2, 2, 0.35, 0.9, 1.6, -0.33, 2.4]
const HIP_PROBES = [0, 1, 11767, 91262, 120415, 999999]

function resolveRepoRoot() {
  return path.resolve(path.dirname(new URL(import.meta.url).pathname), '..', '..')
}

function resolveSourceRoot(repoRoot) {
  const fromEnv = process.env.STELLARIUM_SOURCE_ROOT
  if (fromEnv?.trim()) {
    return path.resolve(fromEnv.trim())
  }
  return path.resolve(
    repoRoot,
    'study/stellarium-web-engine/source/stellarium-web-engine-master',
  )
}

async function getSourceRevision(sourceRoot) {
  try {
    const { stdout } = await execFile('git', ['-C', sourceRoot, 'rev-parse', 'HEAD'])
    return stdout.trim()
  } catch {
    return PINNED_SOURCE_REVISION
  }
}

function buildHelperProgram() {
  const bvProbeInitializers = BV_PROBES.map((value) => `${value}`).join(', ')
  const hipProbeInitializers = HIP_PROBES.map((value) => `${value}`).join(', ')

  return String.raw`#include <math.h>
#include <stdio.h>
#include <stdint.h>

void bv_to_rgb(double bv, double rgb[3]);
int hip_get_pix(int hip, int order);

int main(void) {
    const double bv_probes[] = { ${bvProbeInitializers} };
    const int hip_probes[] = { ${hipProbeInitializers} };
    const int bv_count = sizeof(bv_probes) / sizeof(bv_probes[0]);
    const int hip_count = sizeof(hip_probes) / sizeof(hip_probes[0]);

    for (int i = 0; i < bv_count; i++) {
        double rgb[3] = {0.0, 0.0, 0.0};
        bv_to_rgb(bv_probes[i], rgb);
        printf("BV %.6f %.6f %.6f %.6f\n", bv_probes[i], rgb[0], rgb[1], rgb[2]);
    }

    for (int i = 0; i < hip_count; i++) {
        const int hip = hip_probes[i];
        const int o0 = hip_get_pix(hip, 0);
        const int o1 = hip_get_pix(hip, 1);
        const int o2 = hip_get_pix(hip, 2);
        printf("HIP %d %d %d %d\n", hip, o0, o1, o2);
    }
    return 0;
}
`
}

function parseHelperOutput(stdout) {
  const bvProbes = []
  const hipProbes = []

  for (const rawLine of stdout.split('\n')) {
    const line = rawLine.trim()
    if (!line) {
      continue
    }

    const parts = line.split(/\s+/)
    if (parts[0] === 'BV' && parts.length === 5) {
      bvProbes.push({
        bv: Number(parts[1]),
        expectedRgb: [
          Number(parts[2]),
          Number(parts[3]),
          Number(parts[4]),
        ],
      })
      continue
    }

    if (parts[0] === 'HIP' && parts.length === 5) {
      hipProbes.push({
        hip: Number(parts[1]),
        expectedByOrder: {
          0: Number(parts[2]),
          1: Number(parts[3]),
          2: Number(parts[4]),
        },
      })
    }
  }

  return { bvProbes, hipProbes }
}

function formatGeneratedFile({ sourceRevision, bvProbes, hipProbes }) {
  const renderedBv = bvProbes
    .map((probe) => {
      const [r, g, b] = probe.expectedRgb
      return `  { bv: ${probe.bv}, expectedRgb: [${r}, ${g}, ${b}] as const },`
    })
    .join('\n')

  const renderedHip = hipProbes
    .map((probe) => {
      const values = probe.expectedByOrder
      return (
        '  { hip: ' +
        `${probe.hip}, expectedByOrder: { 0: ${values[0]}, 1: ${values[1]}, 2: ${values[2]} } as const },`
      )
    })
    .join('\n')

  return `// This file is generated by frontend/scripts/generate_module2_side_by_side_reference.mjs\n// Source: study/stellarium-web-engine/source/stellarium-web-engine-master\n\nexport const MODULE2_SIDE_BY_SIDE_SOURCE_REVISION =\n  '${sourceRevision}' as const\n\nexport const MODULE2_SIDE_BY_SIDE_BV_PROBES = [\n${renderedBv}\n] as const\n\nexport const MODULE2_SIDE_BY_SIDE_HIP_PROBES = [\n${renderedHip}\n] as const\n`
}

async function main() {
  const repoRoot = resolveRepoRoot()
  const sourceRoot = resolveSourceRoot(repoRoot)

  const helperProgramPath = path.join(os.tmpdir(), `module2-side-by-side-${Date.now()}.c`)
  const helperBinaryPath = path.join(os.tmpdir(), `module2-side-by-side-${Date.now()}`)

  try {
    await fs.writeFile(helperProgramPath, buildHelperProgram(), 'utf8')

    await execFile('gcc', [
      '-std=c99',
      '-O2',
      '-I',
      path.join(sourceRoot, 'src'),
      helperProgramPath,
      path.join(sourceRoot, 'src/algos/bv_to_rgb.c'),
      path.join(sourceRoot, 'src/hip.c'),
      '-lm',
      '-o',
      helperBinaryPath,
    ])

    const { stdout } = await execFile(helperBinaryPath, [])
    const helperOutput = parseHelperOutput(stdout)

    const sourceRevision = await getSourceRevision(sourceRoot)
    if (sourceRevision !== PINNED_SOURCE_REVISION) {
      console.warn(
        `[generate_module2_side_by_side_reference] warning: source revision ${sourceRevision} differs from pinned ${PINNED_SOURCE_REVISION}`,
      )
    }

    const generatedPath = path.resolve(
      repoRoot,
      'frontend/src/features/sky-engine/engine/sky/runtime/module2SideBySideReference.generated.ts',
    )

    const generatedContent = formatGeneratedFile({
      sourceRevision,
      bvProbes: helperOutput.bvProbes,
      hipProbes: helperOutput.hipProbes,
    })

    await fs.writeFile(generatedPath, generatedContent, 'utf8')
    console.log(`[generate_module2_side_by_side_reference] wrote ${generatedPath}`)
  } finally {
    await Promise.allSettled([
      fs.unlink(helperProgramPath),
      fs.unlink(helperBinaryPath),
    ])
  }
}

try {
  await main()
} catch (error) {
  console.error('[generate_module2_side_by_side_reference] failed')
  console.error(error)
  process.exit(1)
}
