/**
 * One-shot generator: reads ERFA `eraNut00a` tables from study/erfa.c and emits
 * `erfaNut00aTables.generated.ts`. Re-run when bumping ERFA sources.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ERFA_C = path.resolve(
  __dirname,
  '../../study/stellarium-web-engine/source/stellarium-web-engine-master/ext_src/erfa/erfa.c',
)

function extractBlock(lines, startLine1, endLine1) {
  return lines.slice(startLine1 - 1, endLine1).join('\n')
}

/** Pull `{ ... },` or `{ ... }` initializer bodies from a C array block. */
function parseBraceEntries(block) {
  const entries = []
  let depth = 0
  let start = -1
  for (let i = 0; i < block.length; i += 1) {
    const c = block[i]
    if (c === '{') {
      if (depth === 0) start = i + 1
      depth += 1
    } else if (c === '}') {
      depth -= 1
      if (depth === 0 && start >= 0) {
        entries.push(block.slice(start, i))
        start = -1
      }
    }
  }
  return entries
}

function numsFromEntry(s) {
  const out = []
  const re = /[-+]?(?:\d+\.?\d*|\d*\.\d+)(?:[eE][-+]?\d+)?/g
  let m
  while ((m = re.exec(s)) !== null) {
    out.push(Number(m[0]))
  }
  return out
}

const lines = fs.readFileSync(ERFA_C, 'utf8').split(/\r?\n/)

// eraNut00a: xls table lines 16436–17249 (1-based), xpl 17280–18103
const xlsBlock = extractBlock(lines, 16436, 17249)
const xplBlock = extractBlock(lines, 17280, 18103)

const xlsEntries = parseBraceEntries(xlsBlock).map(numsFromEntry)
const xplEntries = parseBraceEntries(xplBlock).map(numsFromEntry)

for (const row of xlsEntries) {
  if (row.length !== 11) {
    throw new Error(`xls row expected 11 numbers, got ${row.length}`)
  }
}
for (let i = 0; i < xplEntries.length; i += 1) {
  const row = xplEntries[i]
  if (row.length !== 17) {
    throw new Error(`xpl row ${i + 1} expected 17 numbers, got ${row.length}: ${JSON.stringify(row)}`)
  }
}

const header = `/**
 * AUTO-GENERATED by scripts/generate_erfa_nut00a_tables.mjs — do not edit.
 * Source: ext_src/erfa/erfa.c (eraNut00a luni-solar + planetary tables).
 */

`

const body = `${header}export const ERFA_NUT00A_XLS: ReadonlyArray<readonly [number, number, number, number, number, number, number, number, number, number, number]> = [
${xlsEntries.map((r) => `  [${r.join(', ')}],`).join('\n')}
]

export const ERFA_NUT00A_XPL: ReadonlyArray<readonly [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number]> = [
${xplEntries.map((r) => `  [${r.join(', ')}],`).join('\n')}
]
`

const outPath = path.resolve(__dirname, '../src/features/sky-engine/engine/sky/runtime/erfaNut00aTables.generated.ts')
fs.writeFileSync(outPath, body, 'utf8')
console.log(`Wrote ${outPath} (${xlsEntries.length} xls, ${xplEntries.length} xpl)`)
