#!/usr/bin/env node
import fs from 'node:fs/promises'
import path from 'node:path'
import { execFile as execFileCb } from 'node:child_process'
import { promisify } from 'node:util'
import { chromium } from '@playwright/test'

const execFile = promisify(execFileCb)

const PINNED_SOURCE_REVISION = '63fb3279e85782158a6df63649f1c8a1837b7846'
const DEFAULT_STELLARIUM_REFERENCE_URL = 'http://127.0.0.1:8080/'

function resolveRepoRoot() {
  return path.resolve(path.dirname(new URL(import.meta.url).pathname), '..', '..')
}

function resolveReferenceUrl() {
  return process.env.STELLARIUM_REFERENCE_URL?.trim() || DEFAULT_STELLARIUM_REFERENCE_URL
}

async function getSourceRevision(sourceRoot) {
  try {
    const { stdout } = await execFile('git', ['-C', sourceRoot, 'rev-parse', 'HEAD'])
    return stdout.trim()
  } catch {
    return PINNED_SOURCE_REVISION
  }
}

function collapseLifecycleCodes(codes) {
  const lifecycle = []
  for (const code of codes) {
    const value = code === 2 ? 'again' : code === 0 ? 'ok' : 'error'
    if (lifecycle[lifecycle.length - 1] !== value) {
      lifecycle.push(value)
    }
    if (value === 'ok' || value === 'error') {
      break
    }
  }
  return lifecycle
}

function asLiteral(value) {
  return JSON.stringify(value, null, 2)
}

function formatGeneratedFile(payload) {
  return `// This file is generated by frontend/scripts/generate_module2_live_side_by_side_reference.mjs
// Source runtime: ${payload.referenceUrl}

export const MODULE2_SIDE_BY_SIDE_LIVE_SOURCE_REVISION =
  '${payload.sourceRevision}' as const

export const MODULE2_SIDE_BY_SIDE_LIVE_REFERENCE_URL =
  ${asLiteral(payload.referenceUrl)} as const

export const MODULE2_SIDE_BY_SIDE_LIVE_STARS_LIST_CHECKPOINTS: ReadonlyArray<{
  id: string
  maxMag: number
  count: number
  sampleIds: readonly string[]
}> = ${asLiteral(payload.starsListCheckpoints)}

export const MODULE2_SIDE_BY_SIDE_LIVE_ADD_DATA_SOURCE_CHECKPOINTS: ReadonlyArray<{
  id: string
  keyPrefix: string
  url: string
  propertiesHttpStatus: number | null
  propertiesText: string | null
  observedCodes: readonly number[]
  observedLifecycle: readonly ('again' | 'ok' | 'error')[]
}> = ${asLiteral(payload.addDataSourceCheckpoints)}
`
}

async function captureLiveReference(referenceUrl) {
  const browser = await chromium.launch({ headless: true })
  const page = await browser.newPage()
  try {
    await page.goto(referenceUrl, { waitUntil: 'networkidle', timeout: 120000 })
    await page.waitForFunction(() => {
      const vm = document.getElementById('app')?.__vue__
      return Boolean(vm?.$stel?.core?.stars?.v)
    }, null, { timeout: 120000 })

    return await page.evaluate(async () => {
      const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
      const vm = document.getElementById('app').__vue__
      const $stel = vm.$stel
      const core = $stel.core
      const stars = core.stars
      const observer = $stel.observer

      const listCheckpoints = [3, 6, 9].map((maxMag) => {
        const objs = stars.listObjs(observer, maxMag, () => true)
        const sampleIds = objs.slice(0, 8).map((obj) => String(obj.id))
        const count = objs.length
        for (const obj of objs) {
          obj.destroy()
        }
        return {
          id: `list-max-${maxMag}`,
          maxMag,
          count,
          sampleIds,
        }
      })

      const moduleAddDataSource = $stel.cwrap('module_add_data_source', 'number', ['number', 'string', 'string'])
      const origin = location.origin
      const probes = [
        {
          id: 'add-stars-minimal',
          keyPrefix: 'live-stars-minimal',
          url: `${origin}/remote-data/swe-data-packs/minimal/2020-09-01/minimal_2020-09-01_186e7ee2/stars`,
        },
        {
          id: 'add-stars-missing',
          keyPrefix: 'live-stars-missing',
          url: `${origin}/remote-data/does-not-exist/stars`,
        },
        {
          id: 'add-stars-wrong-type',
          keyPrefix: 'live-stars-wrong-type',
          url: `${origin}/remote-data/swe-data-packs/base/2020-09-01/base_2020-09-01_1aa210df/dso`,
        },
      ]

      const addDataSourceCheckpoints = []
      for (const probe of probes) {
        const observedCodes = []
        for (let index = 0; index < 8; index += 1) {
          observedCodes.push(moduleAddDataSource(stars.v, probe.url, `${probe.keyPrefix}-${index}`))
          await delay(250)
        }

        let propertiesHttpStatus = null
        let propertiesText = null
        try {
          const response = await fetch(`${probe.url}/properties`)
          propertiesHttpStatus = response.status
          if (response.ok) {
            propertiesText = await response.text()
          }
        } catch {
          propertiesHttpStatus = null
          propertiesText = null
        }

        addDataSourceCheckpoints.push({
          ...probe,
          propertiesHttpStatus,
          propertiesText,
          observedCodes,
        })
      }

      return {
        starsListCheckpoints: listCheckpoints,
        addDataSourceCheckpoints,
      }
    })
  } finally {
    await browser.close()
  }
}

async function main() {
  const repoRoot = resolveRepoRoot()
  const sourceRoot = path.resolve(
    repoRoot,
    'study/stellarium-web-engine/source/stellarium-web-engine-master',
  )
  const referenceUrl = resolveReferenceUrl()

  const [sourceRevision, live] = await Promise.all([
    getSourceRevision(sourceRoot),
    captureLiveReference(referenceUrl),
  ])

  if (sourceRevision !== PINNED_SOURCE_REVISION) {
    console.warn(
      `[generate_module2_live_side_by_side_reference] warning: source revision ${sourceRevision} differs from pinned ${PINNED_SOURCE_REVISION}`,
    )
  }

  const output = {
    sourceRevision,
    referenceUrl,
    starsListCheckpoints: live.starsListCheckpoints,
    addDataSourceCheckpoints: live.addDataSourceCheckpoints.map((checkpoint) => ({
      ...checkpoint,
      observedLifecycle: collapseLifecycleCodes(checkpoint.observedCodes),
    })),
  }

  const outputPath = path.resolve(
    repoRoot,
    'frontend/src/features/sky-engine/engine/sky/runtime/module2SideBySideLiveReference.generated.ts',
  )
  await fs.writeFile(outputPath, formatGeneratedFile(output), 'utf8')
  console.log(`[generate_module2_live_side_by_side_reference] wrote ${outputPath}`)
}

try {
  await main()
} catch (error) {
  console.error('[generate_module2_live_side_by_side_reference] failed')
  console.error(error)
  process.exit(1)
}
