/**
 * One-shot generator: reads ERFA `eraEpv00` harmonic tables from study `erfa.c` and emits
 * `erfaEpv00Tables.generated.ts`. Re-run when bumping ERFA sources.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ERFA_C = path.resolve(
  __dirname,
  '../../study/stellarium-web-engine/source/stellarium-web-engine-master/ext_src/erfa/erfa.c',
)

const TABLE_NAMES = [
  'e0x',
  'e0y',
  'e0z',
  'e1x',
  'e1y',
  'e1z',
  'e2x',
  'e2y',
  'e2z',
  's0x',
  's0y',
  's0z',
  's1x',
  's1y',
  's1z',
  's2x',
  's2y',
  's2z',
]

function extractArrayBody(text, name) {
  const marker = `static const double ${name}[] = {`
  const start = text.indexOf(marker)
  if (start < 0) {
    throw new Error(`Missing array ${name} in ${ERFA_C}`)
  }
  let pos = start + marker.length
  let depth = 1
  while (pos < text.length && depth > 0) {
    const c = text[pos]
    if (c === '{') depth += 1
    else if (c === '}') depth -= 1
    pos += 1
  }
  if (depth !== 0) {
    throw new Error(`Unbalanced braces for ${name}`)
  }
  return text.slice(start + marker.length, pos - 1)
}

function numsFromBlock(inner) {
  const re = /[-+]?(?:\d+\.?\d*|\d*\.\d+)(?:[eE][-+]?\d+)?/g
  const out = []
  let m
  while ((m = re.exec(inner)) !== null) {
    out.push(Number(m[0]))
  }
  return out
}

const text = fs.readFileSync(ERFA_C, 'utf8')
const exports = []

for (const name of TABLE_NAMES) {
  const inner = extractArrayBody(text, name)
  const nums = numsFromBlock(inner)
  if (nums.length === 0 || nums.length % 3 !== 0) {
    throw new Error(`${name}: expected non-zero multiple of 3 numbers, got ${nums.length}`)
  }
  const tsName = `ERFA_EPV00_${name.toUpperCase()}`
  exports.push(
    `export const ${tsName}: readonly number[] = [\n${nums.map((n) => `  ${String(n)},`).join('\n')}\n] as const\n`,
  )
}

const header = `/**
 * AUTO-GENERATED by scripts/generate_erfa_epv00_tables.mjs — do not edit.
 * Source: ext_src/erfa/erfa.c (\`eraEpv00\` VSOP2000 harmonic coefficients).
 * Each flat array is (amplitude, phase, frequency) triplets per ERFA comments.
 */

`

const outPath = path.resolve(__dirname, '../src/features/sky-engine/engine/sky/runtime/erfaEpv00Tables.generated.ts')
fs.writeFileSync(outPath, header + exports.join('\n'), 'utf8')
console.log(`Wrote ${outPath} (${TABLE_NAMES.length} tables)`)
