// This file is generated by frontend/scripts/generate_module2_live_side_by_side_reference.mjs
// Source runtime: http://127.0.0.1:8080/

export const MODULE2_SIDE_BY_SIDE_LIVE_SOURCE_REVISION =
  '63fb3279e85782158a6df63649f1c8a1837b7846' as const

export const MODULE2_SIDE_BY_SIDE_LIVE_REFERENCE_URL =
  "http://127.0.0.1:8080/" as const

export const MODULE2_SIDE_BY_SIDE_LIVE_STARS_LIST_CHECKPOINTS: ReadonlyArray<{
  id: string
  maxMag: number
  count: number
  sampleIds: readonly string[]
}> = [
  {
    "id": "list-max-3",
    "maxMag": 3,
    "count": 1,
    "sampleIds": [
      "NAME Capella"
    ]
  },
  {
    "id": "list-max-6",
    "maxMag": 6,
    "count": 1,
    "sampleIds": [
      "NAME Capella"
    ]
  },
  {
    "id": "list-max-9",
    "maxMag": 9,
    "count": 1,
    "sampleIds": [
      "NAME Capella"
    ]
  }
]

export const MODULE2_SIDE_BY_SIDE_LIVE_ADD_DATA_SOURCE_CHECKPOINTS: ReadonlyArray<{
  id: string
  keyPrefix: string
  url: string
  propertiesHttpStatus: number | null
  propertiesText: string | null
  observedCodes: readonly number[]
  observedLifecycle: readonly ('again' | 'ok' | 'error')[]
}> = [
  {
    "id": "add-stars-minimal",
    "keyPrefix": "live-stars-minimal",
    "url": "http://127.0.0.1:8080/remote-data/swe-data-packs/minimal/2020-09-01/minimal_2020-09-01_186e7ee2/stars",
    "propertiesHttpStatus": 200,
    "propertiesText": "obs_description          = minimal stars survey for Stellarium Mobile\nhips_release_date        = 2020-02-05T00:00Z\nhips_order_min           = 0\nmin_vmag                 = -1.0859375\nmax_vmag                 = 7.0\ntype                     = stars\nhips_tile_format         = eph\nskysource_sha256         = 9a69fa539def81a1cbf94049111e2175b927055376ca5fb256fc6c80e655ab95\n",
    "observedCodes": [
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "observedLifecycle": [
      "again",
      "ok"
    ]
  },
  {
    "id": "add-stars-missing",
    "keyPrefix": "live-stars-missing",
    "url": "http://127.0.0.1:8080/remote-data/does-not-exist/stars",
    "propertiesHttpStatus": 403,
    "propertiesText": null,
    "observedCodes": [
      2,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1
    ],
    "observedLifecycle": [
      "again",
      "error"
    ]
  },
  {
    "id": "add-stars-wrong-type",
    "keyPrefix": "live-stars-wrong-type",
    "url": "http://127.0.0.1:8080/remote-data/swe-data-packs/base/2020-09-01/base_2020-09-01_1aa210df/dso",
    "propertiesHttpStatus": 200,
    "propertiesText": "obs_description          = base DSO survey for Stellarium Mobile\nhips_release_date        = 2020-02-05T00:00Z\nhips_order_min           = 0\ntype                     = dso\nhips_tile_format         = eph\nskysource_sha256         = bc38defabe26141d1acf3b1cda2414e44c3e8217a82fae25930097e8ee520b2c\n",
    "observedCodes": [
      2,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1
    ],
    "observedLifecycle": [
      "again",
      "error"
    ]
  }
]
