// This file is generated by frontend/scripts/generate_module2_side_by_side_reference.mjs
// Source: study/stellarium-web-engine/source/stellarium-web-engine-master

export const MODULE2_SIDE_BY_SIDE_SOURCE_REVISION =
  '63fb3279e85782158a6df63649f1c8a1837b7846' as const

export const MODULE2_SIDE_BY_SIDE_BV_PROBES = [
  { bv: -0.2, expectedRgb: [0.697764, 0.786929, 1] as const },
  { bv: 0, expectedRgb: [0.798196, 0.858824, 1] as const },
  { bv: 0.58, expectedRgb: [1, 0.998574, 0.997148] as const },
  { bv: 1.2, expectedRgb: [1, 0.931881, 0.854321] as const },
  { bv: 2, expectedRgb: [1, 0.81734, 0.596904] as const },
  { bv: 0.35, expectedRgb: [0.964444, 0.972549, 1] as const },
  { bv: 0.9, expectedRgb: [1, 0.981263, 0.960349] as const },
  { bv: 1.6, expectedRgb: [1, 0.867683, 0.716485] as const },
  { bv: -0.33, expectedRgb: [0.613529, 0.721569, 1] as const },
  { bv: 2.4, expectedRgb: [1, 0.782848, 0.533824] as const },
] as const

export const MODULE2_SIDE_BY_SIDE_HIP_PROBES = [
  { hip: 0, expectedByOrder: { 0: -1, 1: -1, 2: -1 } as const },
  { hip: 1, expectedByOrder: { 0: 4, 1: 19, 2: 76 } as const },
  { hip: 11767, expectedByOrder: { 0: 0, 1: 3, 2: 15 } as const },
  { hip: 91262, expectedByOrder: { 0: 3, 1: 14, 2: 58 } as const },
  { hip: 120415, expectedByOrder: { 0: 11, 1: 44, 2: 178 } as const },
  { hip: 999999, expectedByOrder: { 0: -1, 1: -1, 2: -1 } as const },
] as const
