import React,{useRef,useEffect} from 'react'
import {nextSnap} from './workspaceUiState'
import {IconButton} from './primitives'
export default function BottomSheet({name,title,snap,layers=false,modalAllowed=true,onSnap,onClose,children}:{name:string;title?:string;snap:number;layers?:boolean;modalAllowed?:boolean;onSnap:(snap:number)=>void;onClose:()=>void;children:React.ReactNode}){
 const dragged=useRef(false),handle=useRef<HTMLButtonElement>(null),start=useRef<{y:number;at:number}>(),sheet=useRef<HTMLElement>(null),previous=useRef<Element|null>(null);const modal=modalAllowed&&!layers&&snap===640
 useEffect(()=>{previous.current=document.activeElement;handle.current?.focus();return ()=>{if(previous.current instanceof HTMLElement&&previous.current.isConnected)previous.current.focus()}},[])
 useEffect(()=>{const frame=document.querySelector<HTMLIFrameElement>('.ws-stage iframe');if(frame)frame.inert=modal;return ()=>{if(frame)frame.inert=false}},[modal])
 return <section ref={sheet} className={`ws-sheet ws-panel${layers?' ws-sheet--layers':''}${snap===96?' ws-sheet--collapsed':''}`} role={modal?'dialog':'region'} aria-modal={modal||undefined} aria-label={name} style={{'--sheet-height':`${layers?440:snap}px`} as React.CSSProperties} onKeyDown={event=>{if(event.key==='Tab'&&modal){const controls=[...sheet.current!.querySelectorAll<HTMLElement>('button:not(:disabled),a,input')].filter(node=>node.offsetHeight);const first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}}}><div className="ws-sheet-heading"><button ref={handle} className="ws-sheet-handle" aria-label={snap>=640?'Collapse sheet':'Expand sheet'} onClick={()=>{if(dragged.current){dragged.current=false;return}onSnap(snap>=640?360:snap===96?360:640)}} onPointerDown={event=>{dragged.current=false;start.current={y:event.clientY,at:performance.now()};event.currentTarget.setPointerCapture(event.pointerId)}} onPointerUp={event=>{const begin=start.current;if(begin){const delta=event.clientY-begin.y;const next=nextSnap(snap,delta,performance.now()-begin.at);dragged.current=Math.abs(delta)>10;if(snap===96&&delta>80)onClose();else if(next!==snap)onSnap(next);start.current=undefined}}}>{snap===96?<strong>{title||name}</strong>:<span/>}</button><IconButton icon="chevron-down" label="Collapse sheet" onClick={()=>snap===96?onClose():onSnap(snap===640?360:96)}/><IconButton icon="x" label="Close sheet" onClick={onClose}/></div><div className="ws-sheet-content" hidden={snap===96}>{children}</div></section>
}
