import React,{useState} from 'react'
import {Link} from 'react-router-dom'
import {useObserveSkyQuery} from '../observe/queries'
import {categoriesForObjects,categoryForObject,skyEngineUrlForObject,type ObserveContext,type ObserveCategory} from '../observe/model'
import TargetRow from './TargetRow'
const labels:Record<ObserveCategory,string>={all:'All','deep-sky':'Deep sky',stars:'Stars','solar-system':'Solar system',satellites:'Satellites'}
export default function ObserveSurface({context,onSelect,onFocus}:{context:ObserveContext;onSelect:(url:string)=>void;onFocus:(url:string)=>void}){
 const query=useObserveSkyQuery(context),[category,setCategory]=useState<ObserveCategory>('all'),[count,setCount]=useState(8)
 return <><h2>Observe {context.isOras?'from ORAS':'from your location'}</h2>{query.isPending?<p role="status">Checking the sky above you…</p>:query.isError?<><p>Observing data unavailable.</p><button className="ws-link" onClick={()=>void query.refetch()}>Retry Observe</button></>:query.data?<><p className="ws-meta">{new Date(query.data.time).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'})}</p><div className="ws-filters" aria-label="Target categories">{categoriesForObjects(query.data.objects).map(value=><button key={value} aria-pressed={category===value} onClick={()=>{setCategory(value);setCount(8)}}>{labels[value]}</button>)}</div>{query.data.objects.filter(object=>category==='all'||categoryForObject(object)===category).slice(0,count).map(object=>{const url=skyEngineUrlForObject(object);return url?<TargetRow key={`${object.catalog}:${object.source_id}`} target={{name:object.name,url,subtitle:`${object.object_type_label||object.type.replaceAll('_',' ')} · ${object.alt.toFixed(0)}° altitude · ${object.az.toFixed(0)}° azimuth`}} onSelect={onSelect} onFocus={onFocus}/>:null})}{query.data.objects.length>count?<button className="ws-link" onClick={()=>setCount(x=>x+8)}>More targets</button>:null}{!query.data.objects.length?<p>No targets available for this time.</p>:null}</>:null}<p className="ws-meta ws-science">Above the geometric horizon. Visibility does not guarantee detectability.</p><Link className="ws-link" to={`/observe${context.at?'?at='+encodeURIComponent(context.at):''}`}>Open focused Observe</Link></>
}
