import React,{useState} from 'react'
import type {RuntimeMode} from '../../../../packages/runtime-protocol/index.mjs'
import {Icon,CloseButton} from './primitives'
import {formatNightTime} from '../tonight/model'
export type TimeState={requested:string;effective:string|null;live:boolean;pending:boolean;error:boolean}
export function TimeEditor({mode,time,onApply,onNow,onClose}:{mode:RuntimeMode;time:TimeState;onApply:(utc:string)=>void;onNow:()=>void;onClose:()=>void}){
 const [value,setValue]=useState(()=>{const date=new Date(time.requested);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)})
 return <section aria-label="Time details"><div className="ws-panel-heading"><h2>{mode==='earth'?'Time details':'Change time'}</h2><CloseButton onClick={onClose}/></div>{mode==='earth'?<><p>Earth layers use live source time.</p><p className="ws-meta">Requested scene time: {formatNightTime(time.requested)}</p><p className="ws-meta">Effective scene time: {time.effective?formatNightTime(time.effective):'Unavailable'}</p><p className="ws-meta">Satellites, aircraft and weather remain live. Each layer reports its own source time in Layers.</p></>:<form onSubmit={event=>{event.preventDefault();if(Number.isFinite(Date.parse(value)))onApply(new Date(value).toISOString())}}><label htmlFor="ws-date">Date and time · {Intl.DateTimeFormat().resolvedOptions().timeZone}</label><input id="ws-date" type="datetime-local" value={value} required onChange={event=>setValue(event.target.value)}/><div className="ws-actions"><button type="button" onClick={()=>onApply(new Date(Date.parse(time.requested)-3600000).toISOString())}>−1h</button><button type="button" onClick={()=>onApply(new Date(Date.parse(time.requested)+3600000).toISOString())}>+1h</button><button type="button" onClick={onNow}>Now</button><button className="ws-primary" type="submit" disabled={time.pending}>Apply</button></div></form>}{time.error?<p role="status">Time wasn't applied. Your previous effective time is retained.</p>:null}</section>
}
export default function TimeSurface({mode,time,onOpen}:{mode:RuntimeMode;time:TimeState;onOpen:()=>void}){return <div className="ws-time ws-panel ws-chrome" role="group" aria-label="Scene time"><Icon name="clock"/><span className={`ws-badge${mode==='earth'||time.live?' ws-badge--live':''}`}>{mode==='earth'||time.live?'Live':time.pending?'Requested':'Set time'}</span><span className="ws-time-label">{mode==='earth'?'Earth layers use live source time':time.effective?formatNightTime(time.effective):'Current astronomical time'}</span><button data-ws-trigger="time" className="ws-link" onClick={onOpen}>{mode==='earth'?'Time details':'Change time'}<Icon name="chevron-up"/></button></div>}
