import React from 'react'
import {Link} from 'react-router-dom'
import {useTonightQuery} from '../tonight/queries'
import {duration,formatNightTime,identityKey,forecastAtPeak} from '../tonight/model'
import TargetRow from './TargetRow'
import {Icon} from './primitives'
export default function TonightSurface({expanded,onSelect,onFocus}:{expanded:boolean;onSelect:(url:string)=>void;onFocus:(url:string)=>void}){
 const query=useTonightQuery()
 if(query.isPending)return <><h2>Tonight at ORAS</h2><p role="status">Preparing your night plan…</p></>
 if(query.isError||!query.data)return <><h2>Tonight at ORAS</h2><p>Night plan unavailable.</p><button className="ws-link" onClick={()=>void query.refetch()}>Retry night plan</button></>
 const {night,targets,forecast}=query.data.data;const top=query.data.data.top_opportunities.flatMap(id=>targets.filter(t=>identityKey(t)===identityKey(id))).slice(0,expanded?2:1)
 return <><h2>Tonight at ORAS</h2><p className="ws-eyebrow">{night.night_date} · {night.timezone}</p>{night.status==='available'?<><div className="ws-darkness"><strong>{duration(night.dark_duration_minutes)}</strong><span>astronomical<br/>darkness</span></div><div className="ws-night-interval"><div><time>{formatNightTime(night.astronomical_darkness[0]?.start)}</time><time>{formatNightTime(night.astronomical_darkness.at(-1)?.end)}</time></div><span className="ws-night-line"/><p className="ws-meta">Evening darkness → morning twilight</p></div></>:<p>{night.status==='no_astronomical_darkness'?'No astronomical darkness this night.':'Night astronomy unavailable.'}</p>}{night.moon?<div className="ws-moon"><Icon name="moon"/><div>Moon · {Math.round(night.moon.illumination_fraction*100)}% illuminated<p className="ws-meta">{night.moon.altitude_deg.toFixed(0)}° altitude · {formatNightTime(night.moon.time)}</p></div></div>:null}<div className="ws-divider"/><p className="ws-eyebrow">High in the dark sky</p>{top.map(target=><React.Fragment key={identityKey(target)}><TargetRow target={{name:target.name,url:target.sky_engine_url,subtitle:`${target.opportunity.peak_altitude_deg.toFixed(0)}° at peak · ${formatNightTime(target.opportunity.peak_time)}`}} onSelect={onSelect} onFocus={onFocus}/>{expanded&&forecast.status!=='stale'&&forecastAtPeak(target,forecast.hours)?.cloud_cover_pct!=null?<p className="ws-meta">Cloud forecast at peak: {forecastAtPeak(target,forecast.hours)!.cloud_cover_pct}% · {forecast.provider?.startsWith('open_meteo')?'Open-Meteo hourly forecast':forecast.provider}</p>:null}</React.Fragment>)}{!top.length?<p className="ws-meta">No targets available for this night.</p>:null}{expanded&&forecast.status==='unavailable'?<p className="ws-meta">Forecast unavailable. Astronomy facts remain available.</p>:null}<Link className="ws-link" to="/tonight">Full night plan <Icon name="arrow-up-right"/></Link></>
}
