/**
 * Synthetic `SkyTileRepositoryLoadResult` fixtures for module1 G4 fingerprint replay (no I/O).
 */
import type { SkyTileRepositoryLoadResult } from '../src/features/sky-engine/engine/sky/contracts/tiles'

export const MODULE1_REPLAY_FIXTURES = [
  {
    id: 'hipparcos-single-tile',
    result: {
      mode: 'hipparcos',
      sourceLabel: 'Hipparcos · 1 stars',
      sourceError: null,
      manifest: {
        schemaVersion: 'sky-runtime-tile.v1',
        catalog: 'hipparcos',
        tileIndex: 'equatorial-quadtree-v1',
        generatedAt: '2026-04-06T00:00:00Z',
        generator: 'fixture',
        sourcePath: 'fixtures/hip_main.dat',
        sourceRecordCount: 1,
        maxLevel: 3,
        tileCount: 1,
        totalStarRecords: 1,
        tiles: {
          'root-nw': {
            path: 'tiles/root-nw.json',
            level: 0,
            starCount: 1,
            magMin: 1.98,
            magMax: 1.98,
          },
        },
      },
      tiles: [{
        tileId: 'root-nw',
        level: 0,
        parentTileId: null,
        childTileIds: ['root-nw-nw', 'root-nw-ne'],
        bounds: { raMinDeg: 0, raMaxDeg: 180, decMinDeg: 0, decMaxDeg: 90 },
        magMin: 1.98,
        magMax: 1.98,
        starCount: 1,
        stars: [{
          id: 'hip-11767',
          sourceId: 'HIP 11767',
          raDeg: 37.954515,
          decDeg: 89.264109,
          mag: 1.98,
          tier: 'T0',
          properName: 'Polaris',
          pmRaMasYr: 3.7,
          pmDecMasYr: -11.9,
          parallaxMas: 7.0,
          colorIndex: 0.02,
        }],
        labelCandidates: [{ starId: 'hip-11767', label: 'Polaris', priority: 180 }],
        provenance: {
          catalog: 'hipparcos',
          sourcePath: 'fixtures/hip_main.dat',
          generator: 'fixture',
        },
      }],
    } satisfies SkyTileRepositoryLoadResult,
  },
  {
    id: 'multi-survey-merge',
    result: {
      mode: 'multi-survey',
      sourceLabel: 'Hipparcos + Gaia HiPS',
      sourceError: null,
      manifest: {
        schemaVersion: 'sky-runtime-tile.v1',
        catalog: 'hipparcos',
        tileIndex: 'equatorial-quadtree-v1',
        generatedAt: '2026-04-06T00:00:00Z',
        generator: 'fixture',
        sourcePath: 'fixtures/hip_main.dat',
        sourceRecordCount: 2,
        maxLevel: 3,
        tileCount: 1,
        totalStarRecords: 2,
        tiles: {
          'root-ne': {
            path: 'tiles/root-ne.json',
            level: 0,
            starCount: 2,
            magMin: 1,
            magMax: 10,
          },
        },
      },
      tiles: [{
        tileId: 'root-ne',
        level: 0,
        parentTileId: null,
        childTileIds: [],
        bounds: { raMinDeg: 180, raMaxDeg: 360, decMinDeg: 0, decMaxDeg: 90 },
        magMin: 1,
        magMax: 10,
        starCount: 2,
        stars: [
          {
            id: 'hip-1',
            raDeg: 185,
            decDeg: 10,
            mag: 1,
            tier: 'T0',
            catalog: 'hipparcos',
          },
          {
            id: 'gaia-1',
            raDeg: 186,
            decDeg: 10.5,
            mag: 9.2,
            tier: 'T2',
            catalog: 'gaia',
          },
        ],
        provenance: { catalog: 'multi-survey', sourcePath: 'hip+gaia' },
      }],
    } satisfies SkyTileRepositoryLoadResult,
  },
  {
    id: 'wrap-bounds-tile',
    result: {
      mode: 'hipparcos',
      sourceLabel: 'Hipparcos wrap test',
      tiles: [{
        tileId: 'wrap',
        level: 1,
        parentTileId: 'root',
        childTileIds: [],
        bounds: { raMinDeg: 350, raMaxDeg: 10, decMinDeg: -5, decMaxDeg: 5 },
        magMin: 2,
        magMax: 8,
        starCount: 1,
        stars: [{
          id: 's1',
          raDeg: 359,
          decDeg: 0,
          mag: 5,
          tier: 'T1',
        }],
      }],
    } satisfies SkyTileRepositoryLoadResult,
  },
] as const
