import fs from 'node:fs'
import path from 'node:path'

import { describe, expect, it } from 'vitest'

const SKY_ENGINE_SCENE_PATH = path.resolve(process.cwd(), 'src/features/sky-engine/SkyEngineScene.tsx')
const SKY_CORE_PATH = path.resolve(process.cwd(), 'src/features/sky-engine/engine/sky/runtime/SkyCore.ts')
const SKY_MODULE_PATH = path.resolve(process.cwd(), 'src/features/sky-engine/engine/sky/runtime/SkyModule.ts')
const SKY_RUNTIME_BRIDGE_PATH = path.resolve(process.cwd(), 'src/features/sky-engine/SkyEngineRuntimeBridge.ts')
const ATMOSPHERE_RUNTIME_MODULE_PATH = path.resolve(process.cwd(), 'src/features/sky-engine/engine/sky/runtime/modules/AtmosphereModule.ts')
const SKY_BRIGHTNESS_EXPOSURE_RUNTIME_MODULE_PATH = path.resolve(process.cwd(), 'src/features/sky-engine/engine/sky/runtime/modules/SkyBrightnessExposureModule.ts')
const LANDSCAPE_RUNTIME_MODULE_PATH = path.resolve(process.cwd(), 'src/features/sky-engine/engine/sky/runtime/modules/LandscapeModule.ts')
const MILKY_WAY_RUNTIME_MODULE_PATH = path.resolve(process.cwd(), 'src/features/sky-engine/engine/sky/runtime/modules/MilkyWayModule.ts')
const BACKGROUND_RUNTIME_MODULE_PATH = path.resolve(process.cwd(), 'src/features/sky-engine/engine/sky/runtime/modules/BackgroundRuntimeModule.ts')
const STARS_RUNTIME_MODULE_PATH = path.resolve(process.cwd(), 'src/features/sky-engine/engine/sky/runtime/modules/StarsModule.ts')
const OBJECT_RUNTIME_MODULE_PATH = path.resolve(process.cwd(), 'src/features/sky-engine/engine/sky/runtime/modules/ObjectRuntimeModule.ts')
const OVERLAY_RUNTIME_MODULE_PATH = path.resolve(process.cwd(), 'src/features/sky-engine/engine/sky/runtime/modules/OverlayRuntimeModule.ts')
const SCENE_REPORTING_RUNTIME_MODULE_PATH = path.resolve(process.cwd(), 'src/features/sky-engine/engine/sky/runtime/modules/SceneReportingModule.ts')
const RUNTIME_FRAME_MODULE_PATH = path.resolve(process.cwd(), 'src/features/sky-engine/engine/sky/runtime/modules/runtimeFrame.ts')

describe('sky core runtime boundary', () => {
  it('moves babylon lifecycle ownership behind SkyCore', () => {
    const sceneSource = fs.readFileSync(SKY_ENGINE_SCENE_PATH, 'utf8')
    const coreSource = fs.readFileSync(SKY_CORE_PATH, 'utf8')
    const moduleSource = fs.readFileSync(SKY_MODULE_PATH, 'utf8')
    const bridgeSource = fs.readFileSync(SKY_RUNTIME_BRIDGE_PATH, 'utf8')

    expect(sceneSource).toContain('new SkyCore')
    expect(sceneSource).not.toContain('new Engine(')
    expect(sceneSource).not.toContain('new Scene(')
    expect(sceneSource).not.toContain('runRenderLoop(')
    expect(sceneSource).not.toContain("addEventListener('wheel'")
    expect(sceneSource).not.toContain("addEventListener('pointerdown'")
    expect(sceneSource).not.toContain('dispatchInput(')
    expect(coreSource).toContain('start()')
    expect(coreSource).toContain('stop()')
    expect(coreSource).toContain('update(deltaSeconds')
    expect(coreSource).toContain('render()')
    expect(coreSource).toContain('registerModule(')
    expect(coreSource).toContain('runRenderLoop')
    expect(coreSource).toContain('startServices')
    expect(coreSource).toContain('updateServices')
    expect(coreSource).toContain('stopServices')
    expect(moduleSource).toContain('renderOrder')
    expect(bridgeSource).toContain('createSkySceneBridgeModule')
    expect(bridgeSource).toContain('createSceneRuntimeState')
  })

  it('registers explicit runtime modules for brightness, atmosphere, milky way, landscape, background, stars, objects, overlays, and reporting', () => {
    const sceneSource = fs.readFileSync(SKY_ENGINE_SCENE_PATH, 'utf8')
    const bridgeSource = fs.readFileSync(SKY_RUNTIME_BRIDGE_PATH, 'utf8')
    const brightnessExposureModuleSource = fs.readFileSync(SKY_BRIGHTNESS_EXPOSURE_RUNTIME_MODULE_PATH, 'utf8')
    const atmosphereModuleSource = fs.readFileSync(ATMOSPHERE_RUNTIME_MODULE_PATH, 'utf8')
    const milkyWayModuleSource = fs.readFileSync(MILKY_WAY_RUNTIME_MODULE_PATH, 'utf8')
    const landscapeModuleSource = fs.readFileSync(LANDSCAPE_RUNTIME_MODULE_PATH, 'utf8')
    const backgroundModuleSource = fs.readFileSync(BACKGROUND_RUNTIME_MODULE_PATH, 'utf8')
    const starsModuleSource = fs.readFileSync(STARS_RUNTIME_MODULE_PATH, 'utf8')
    const objectModuleSource = fs.readFileSync(OBJECT_RUNTIME_MODULE_PATH, 'utf8')
    const overlayModuleSource = fs.readFileSync(OVERLAY_RUNTIME_MODULE_PATH, 'utf8')
    const sceneReportingModuleSource = fs.readFileSync(SCENE_REPORTING_RUNTIME_MODULE_PATH, 'utf8')

    expect(sceneSource).toContain('createSkyBrightnessExposureModule')
    expect(sceneSource).toContain('createAtmosphereModule')
    expect(sceneSource).toContain('createMilkyWayModule')
    expect(sceneSource).toContain('createLandscapeModule')
    expect(sceneSource).toContain('createBackgroundRuntimeModule')
    expect(sceneSource).toContain('createStarsModule')
    expect(sceneSource).toContain('createObjectRuntimeModule')
    expect(sceneSource).toContain('createOverlayRuntimeModule')
    expect(sceneSource).toContain('createSceneReportingModule')

    expect(brightnessExposureModuleSource).toContain("id: 'sky-brightness-exposure-runtime-module'")
    expect(atmosphereModuleSource).toContain("id: 'sky-atmosphere-runtime-module'")
    expect(milkyWayModuleSource).toContain("id: 'sky-milky-way-runtime-module'")
    expect(landscapeModuleSource).toContain("id: 'sky-landscape-runtime-module'")
    expect(backgroundModuleSource).toContain("id: 'sky-background-runtime-module'")
    expect(starsModuleSource).toContain("id: 'sky-stars-runtime-module'")
    expect(objectModuleSource).toContain("id: 'sky-object-runtime-module'")
    expect(overlayModuleSource).toContain("id: 'sky-overlay-runtime-module'")
    expect(sceneReportingModuleSource).toContain("id: 'sky-scene-reporting-runtime-module'")
    expect(brightnessExposureModuleSource).toContain('computeSkyBrightness(')
    expect(brightnessExposureModuleSource).toContain('computeEffectiveLimitingMagnitude(')
    expect(brightnessExposureModuleSource).toContain('computeNightSkyLuminance(')
    expect(atmosphereModuleSource).toContain('prepareDirectAtmosphereFrame(')
    expect(milkyWayModuleSource).toContain('runtime.brightnessExposureState')
    expect(milkyWayModuleSource).toContain('renderMilkyWayLayer(')
    expect(landscapeModuleSource).toContain('prepareDirectLandscapeFrame(')
    expect(backgroundModuleSource).toContain('drawSyntheticDensityStars(')
    expect(backgroundModuleSource).not.toContain('prepareDirectAtmosphereFrame(')
    expect(backgroundModuleSource).not.toContain('prepareDirectLandscapeFrame(')
    expect(backgroundModuleSource).not.toContain('renderMilkyWayLayer(')
    expect(starsModuleSource).toContain('collectProjectedStars(')
    expect(objectModuleSource).toContain('collectProjectedNonStarObjects(')
    expect(objectModuleSource).not.toContain('collectProjectedStars(')
    expect(sceneReportingModuleSource).toContain('writeSceneState({')
    expect(sceneReportingModuleSource).toContain('writeSkyEnginePickTargets(')

    expect(bridgeSource).not.toContain('function renderSceneFrame')
    expect(bridgeSource).not.toContain('function collectProjectedObjects')
    expect(bridgeSource).not.toContain('function drawSyntheticDensityStars')
  })

  it('registers runtime modules in explicit render order and keeps the bridge last', () => {
    const sceneSource = fs.readFileSync(SKY_ENGINE_SCENE_PATH, 'utf8')
    const brightnessExposureModuleSource = fs.readFileSync(SKY_BRIGHTNESS_EXPOSURE_RUNTIME_MODULE_PATH, 'utf8')
    const atmosphereModuleSource = fs.readFileSync(ATMOSPHERE_RUNTIME_MODULE_PATH, 'utf8')
    const milkyWayModuleSource = fs.readFileSync(MILKY_WAY_RUNTIME_MODULE_PATH, 'utf8')
    const landscapeModuleSource = fs.readFileSync(LANDSCAPE_RUNTIME_MODULE_PATH, 'utf8')
    const backgroundModuleSource = fs.readFileSync(BACKGROUND_RUNTIME_MODULE_PATH, 'utf8')
    const starsModuleSource = fs.readFileSync(STARS_RUNTIME_MODULE_PATH, 'utf8')
    const objectModuleSource = fs.readFileSync(OBJECT_RUNTIME_MODULE_PATH, 'utf8')
    const overlayModuleSource = fs.readFileSync(OVERLAY_RUNTIME_MODULE_PATH, 'utf8')
    const sceneReportingModuleSource = fs.readFileSync(SCENE_REPORTING_RUNTIME_MODULE_PATH, 'utf8')
    const bridgeSource = fs.readFileSync(SKY_RUNTIME_BRIDGE_PATH, 'utf8')

    const brightnessRegistrationIndex = sceneSource.indexOf('core.registerModule(createSkyBrightnessExposureModule())')
    const atmosphereRegistrationIndex = sceneSource.indexOf('core.registerModule(createAtmosphereModule())')
    const milkyWayRegistrationIndex = sceneSource.indexOf('core.registerModule(createMilkyWayModule())')
    const landscapeRegistrationIndex = sceneSource.indexOf('core.registerModule(createLandscapeModule())')
    const backgroundRegistrationIndex = sceneSource.indexOf('core.registerModule(createBackgroundRuntimeModule())')
    const starsRegistrationIndex = sceneSource.indexOf('core.registerModule(createStarsModule())')
    const objectRegistrationIndex = sceneSource.indexOf('core.registerModule(createObjectRuntimeModule())')
    const overlayRegistrationIndex = sceneSource.indexOf('core.registerModule(createOverlayRuntimeModule())')
    const sceneReportingRegistrationIndex = sceneSource.indexOf('core.registerModule(createSceneReportingModule())')
    const bridgeRegistrationIndex = sceneSource.indexOf('core.registerModule(createSkySceneBridgeModule())')

    expect(brightnessRegistrationIndex).toBeGreaterThan(-1)
    expect(atmosphereRegistrationIndex).toBeGreaterThan(brightnessRegistrationIndex)
    expect(atmosphereRegistrationIndex).toBeGreaterThan(-1)
    expect(milkyWayRegistrationIndex).toBeGreaterThan(atmosphereRegistrationIndex)
    expect(landscapeRegistrationIndex).toBeGreaterThan(milkyWayRegistrationIndex)
    expect(backgroundRegistrationIndex).toBeGreaterThan(landscapeRegistrationIndex)
    expect(starsRegistrationIndex).toBeGreaterThan(backgroundRegistrationIndex)
    expect(objectRegistrationIndex).toBeGreaterThan(starsRegistrationIndex)
    expect(overlayRegistrationIndex).toBeGreaterThan(objectRegistrationIndex)
    expect(sceneReportingRegistrationIndex).toBeGreaterThan(overlayRegistrationIndex)
    expect(bridgeRegistrationIndex).toBeGreaterThan(sceneReportingRegistrationIndex)

    expect(brightnessExposureModuleSource).toContain('renderOrder: 5')
    expect(atmosphereModuleSource).toContain('renderOrder: 10')
    expect(milkyWayModuleSource).toContain('renderOrder: 12')
    expect(landscapeModuleSource).toContain('renderOrder: 15')
    expect(backgroundModuleSource).toContain('renderOrder: 18')
    expect(starsModuleSource).toContain('renderOrder: 20')
    expect(objectModuleSource).toContain('renderOrder: 30')
    expect(overlayModuleSource).toContain('renderOrder: 40')
    expect(sceneReportingModuleSource).toContain('renderOrder: 90')
    expect(bridgeSource).toContain('renderOrder: 100')
  })

  it('keeps the bridge as a thin navigation compatibility shell instead of report ownership', () => {
    const bridgeSource = fs.readFileSync(SKY_RUNTIME_BRIDGE_PATH, 'utf8')
    const sceneReportingModuleSource = fs.readFileSync(SCENE_REPORTING_RUNTIME_MODULE_PATH, 'utf8')

    expect(bridgeSource).not.toContain('writeSceneState({')
    expect(bridgeSource).not.toContain('writeSkyEnginePickTargets')
    expect(bridgeSource).not.toContain('buildSkyEnginePickTargets')
    expect(sceneReportingModuleSource).toContain('writeSceneState({')
    expect(sceneReportingModuleSource).toContain('writeSkyEnginePickTargets')
    expect(sceneReportingModuleSource).toContain('clearSceneState(')
    expect(sceneReportingModuleSource).toContain('clearSkyEnginePickTargets(')
    expect(bridgeSource).not.toContain('prepareDirectBackgroundFrame')
    expect(bridgeSource).not.toContain('prepareDirectLandscapeFrame')
    expect(bridgeSource).not.toContain('prepareDirectOverlayFrame')
    expect(bridgeSource).not.toContain('collectProjectedObjects(')
    expect(bridgeSource).not.toContain('runtime.directObjectLayer.sync(')
    expect(bridgeSource).not.toContain('runtime.directOverlayLayer.sync(')
    expect(bridgeSource).not.toContain('runtime.directBackgroundLayer.sync(')
  })

  it('centralizes sky brightness and exposure ownership before atmosphere and stars consume it', () => {
    const brightnessExposureModuleSource = fs.readFileSync(SKY_BRIGHTNESS_EXPOSURE_RUNTIME_MODULE_PATH, 'utf8')
    const atmosphereModuleSource = fs.readFileSync(ATMOSPHERE_RUNTIME_MODULE_PATH, 'utf8')
    const starsModuleSource = fs.readFileSync(STARS_RUNTIME_MODULE_PATH, 'utf8')
    const backgroundModuleSource = fs.readFileSync(BACKGROUND_RUNTIME_MODULE_PATH, 'utf8')
    const runtimeFrameSource = fs.readFileSync(RUNTIME_FRAME_MODULE_PATH, 'utf8')

    expect(brightnessExposureModuleSource).toContain('runtime.brightnessExposureState =')
    expect(brightnessExposureModuleSource).toContain('limitingMagnitude')
    expect(brightnessExposureModuleSource).toContain('starVisibility')
    expect(brightnessExposureModuleSource).toContain('starFieldBrightness')
    expect(brightnessExposureModuleSource).toContain('atmosphereExposure')
    expect(brightnessExposureModuleSource).toContain('milkyWayVisibility')
    expect(brightnessExposureModuleSource).toContain('milkyWayContrast')
    expect(atmosphereModuleSource).toContain('runtime.brightnessExposureState')
    expect(fs.readFileSync(MILKY_WAY_RUNTIME_MODULE_PATH, 'utf8')).toContain('runtime.brightnessExposureState')
    expect(starsModuleSource).toContain('runtime.brightnessExposureState')
    expect(backgroundModuleSource).toContain('runtime.brightnessExposureState')
    expect(runtimeFrameSource).not.toContain('computeSkyBrightness(')
    expect(runtimeFrameSource).not.toContain('computeEffectiveLimitingMagnitude(')
  })
})
