import React from 'react'
import {renderToStaticMarkup} from 'react-dom/server'
import {afterEach,describe,it,expect,vi} from 'vitest'
const hooks=vi.hoisted(()=>({effects:[] as (()=>(()=>void)|void)[],set:vi.fn()}))
vi.mock('react',async original=>({...await original<typeof import('react')>(),useEffect:(effect:()=>void)=>hooks.effects.push(effect),useState:(initial:any)=>[typeof initial==='function'?initial():initial,hooks.set]}))
import TimeSurface,{TimeEditor} from '../src/features/workspace/TimeSurface'
const time={requested:'2026-10-03T02:00:00.000Z',effective:'2026-10-03T03:00:00.000Z',live:true,pending:false,error:false}
const nodes=(node:any):any[]=>!node||typeof node!=='object'?[]:[node,...React.Children.toArray(node.props?.children).flatMap(nodes)]
afterEach(()=>{vi.useRealTimers();hooks.effects=[];hooks.set.mockClear()})
describe('workspace scene time',()=>{
 it('uses current Live clock and ticks once per second with cleanup',()=>{vi.useFakeTimers();vi.setSystemTime('2026-10-03T10:00:00Z');expect(renderToStaticMarkup(<TimeSurface mode="sky" time={time} isOras={false} onOpen={()=>{}}/>)).toContain('10:00');const cleanups=hooks.effects.map(effect=>effect());hooks.set.mockClear();vi.advanceTimersByTime(2000);expect(hooks.set).toHaveBeenCalledTimes(2);expect(hooks.set).toHaveBeenLastCalledWith(Date.now());vi.advanceTimersByTime(58000);expect(renderToStaticMarkup(<TimeSurface mode="sky" time={time} isOras={false} onOpen={()=>{}}/>)).toContain('10:01');cleanups.forEach(cleanup=>cleanup?.());expect(vi.getTimerCount()).toBe(0)})
 it.each([['+1h',1],['−1h',-1]])('Live %s uses current clock at click', (label,offset)=>{vi.useFakeTimers();vi.setSystemTime('2026-10-03T10:00:00Z');const apply=vi.fn(),editor=TimeEditor({mode:'sky',time,isOras:false,onApply:apply,onNow:()=>{},onClose:()=>{}});vi.setSystemTime('2026-10-03T12:00:00Z');nodes(editor).find(n=>n.type==='button'&&n.props.children===label).props.onClick();expect(apply).toHaveBeenCalledWith(new Date(Date.now()+Number(offset)*3600000).toISOString())})
 it('fixed effective display and requested offset do not drift or start timers',()=>{vi.useFakeTimers();vi.setSystemTime('2026-10-03T10:00:00Z');const fixed={...time,live:false},apply=vi.fn();const before=renderToStaticMarkup(<TimeSurface mode="sky" time={fixed} isOras={false} onOpen={()=>{}}/>);hooks.effects.forEach(effect=>effect());expect(vi.getTimerCount()).toBe(0);vi.advanceTimersByTime(3600000);expect(renderToStaticMarkup(<TimeSurface mode="sky" time={fixed} isOras={false} onOpen={()=>{}}/>)).toBe(before);const editor=TimeEditor({mode:'sky',time:fixed,isOras:false,onApply:apply,onNow:()=>{},onClose:()=>{}});nodes(editor).find(n=>n.type==='button'&&n.props.children==='+1h').props.onClick();expect(apply).toHaveBeenCalledWith(time.effective)})
 it.each([[true,'EDT','America/New_York','2026-10-02T22:00','2026-10-03T02:00:00.000Z'],[false,'UTC','UTC','2026-10-03T02:00','2026-10-03T02:00:00.000Z']])('observer ORAS=%s formats requested/effective and input in one timezone', (isOras,zone,label,value,utc)=>{const fixed={...time,live:false},apply=vi.fn();const details=renderToStaticMarkup(<TimeEditor mode="earth" time={fixed} isOras={isOras} onApply={apply} onNow={()=>{}} onClose={()=>{}}/>);expect(details.match(new RegExp(zone,'g'))).toHaveLength(2);const editor=TimeEditor({mode:'sky',time:fixed,isOras,onApply:apply,onNow:()=>{},onClose:()=>{}});expect(nodes(editor).find(n=>n.type==='label').props.children.join('')).toContain(label);expect(nodes(editor).find(n=>n.type==='input').props.value).toBe(value);nodes(editor).find(n=>n.type==='form').props.onSubmit({preventDefault(){}});expect(apply).toHaveBeenCalledWith(utc)})
})
