FROM emscripten/emsdk:1.39.17

RUN printf 'Acquire::Check-Valid-Until "false";\n' > /etc/apt/apt.conf.d/99archive \
 && printf '%s\n%s\n' \
  'deb http://archive.debian.org/debian buster main' \
  'deb http://archive.debian.org/debian buster-updates main' > /etc/apt/sources.list \
 && apt-get update -o Acquire::Check-Valid-Until=false \
 && apt-get install -y --no-install-recommends wget build-essential apt-transport-https scons \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

EXPOSE 8000