import test from 'node:test';import assert from 'node:assert/strict';
import {validEventFeed,validRadarFeed} from '../../runtimes/earth-runtime/layers/eventData.mjs';
const stamp=new Date().toISOString();const record={id:'fixture',name:'Fixture',lat:42,lon:-80,occurredAt:stamp,updatedAt:stamp,magnitude:3,depthKm:10,acres:null,containedPct:null,polygons:null};
const feed={schemaVersion:1,kind:'earthquakes',temporalMode:'EVENT_FEED',source:'USGS',observedAt:stamp,fetchedAt:stamp,records:[record],limited:false};
test('event DTO preserves exact IDs/source times and accepts empty snapshot',()=>{assert.ok(validEventFeed(feed,'earthquakes'));assert.ok(validEventFeed({...feed,records:[]},'earthquakes'));assert.equal(validEventFeed({...feed,records:[{...record,id:4}]},'earthquakes'),false)});
test('event contract rejects raw blobs, invalid coordinates, duplicate IDs and cap excess',()=>{for(const records of [[{...record,raw:{}}],[{...record,lat:NaN}],[record,record],Array.from({length:501},(_,i)=>({...record,id:String(i)}))])assert.equal(validEventFeed({...feed,records},'earthquakes'),false);assert.equal(validEventFeed({...feed,temporalMode:'LIVE_ONLY'},'earthquakes'),false)});
test('fire DTO only accepts bounded closed polygons and truthful perimeter semantics',()=>{const fire={...feed,kind:'fire-perimeters',temporalMode:'CURRENT_SNAPSHOT',limited:true,records:[{...record,magnitude:null,depthKm:null,occurredAt:null,polygons:[[[[-80,42],[-79,42],[-79,43],[-80,42]]]]}]};assert.ok(validEventFeed(fire,'fire-perimeters'));fire.records[0].polygons[0][0][0][0]=NaN;assert.equal(validEventFeed(fire,'fire-perimeters'),false)});
test('radar contract pins explicit source time and CONUS coverage without accepting provider blobs',()=>{const radar={schemaVersion:1,product:'radar',temporalMode:'CURRENT_SNAPSHOT',source:'NOAA/NWS nowCOAST',latest:stamp,times:[stamp],bounds:{west:-130,south:20,east:-60,north:55},fetchedAt:stamp,tileSize:256,maxLevel:6,tilingScheme:'geographic'};assert.ok(validRadarFeed(radar));assert.equal(validRadarFeed({...radar,latest:'current'}),false);assert.equal(validRadarFeed({...radar,bounds:{west:-180,south:-90,east:180,north:90}}),false);assert.equal(validRadarFeed({...radar,raw:{}}),false)});

test('recent-event contract rejects events outside its past-day recency window',()=>{assert.equal(validEventFeed({...feed,records:[{...record,occurredAt:'2020-01-01T00:00:00.000Z'}]},'earthquakes'),false)});
