#!/usr/bin/env python3

from __future__ import annotations

import argparse
import hashlib
import json
import math
import shutil
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlparse
from urllib.request import urlopen

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from scripts.skydata.common import REPO_ROOT, write_json
from scripts.skydata.scan_runtime_external_dependencies import scan_runtime_external_dependencies

DEFAULT_TARGET = 'm31'
DEFAULT_SOURCE_ROOT = 'https://alasky.cds.unistra.fr/DSS/DSSColor'
DEFAULT_ORDER_MIN = 0
DEFAULT_ORDER_MAX = 7
DEFAULT_SAMPLE_STEP_DEG = 0.1
DEFAULT_RAW_ROOT = REPO_ROOT / 'data/raw/surveys/dss-proof'
DEFAULT_PROCESSED_ROOT = REPO_ROOT / 'data/processed/surveys/dss-proof'
RUNTIME_READY_RELATIVE_ROOT = Path('runtime-ready/surveys/dss/v1')
RUNTIME_SURVEY_RELATIVE_ROOT = Path('surveys/dss/v1')
VENDOR_RUNTIME_SURVEY_ROOT = REPO_ROOT / 'vendor/stellarium-web-engine/apps/test-skydata/surveys/dss/v1'
PUBLIC_RUNTIME_SURVEY_ROOT = REPO_ROOT / 'frontend/public/oras-sky-engine/skydata/surveys/dss/v1'

TARGETS: dict[str, dict[str, Any]] = {
    'm31': {
        'key': 'm31',
        'label': 'M31',
        'display_name': 'Andromeda Galaxy',
        'ra_deg': 10.6847083,
        'dec_deg': 41.26875,
        'radius_deg': 2.5,
    },
    'c6': {
        'key': 'c6',
        'label': 'C 6',
        'display_name': "Cat's Eye Nebula",
        'ra_deg': 269.64825,
        'dec_deg': 66.63389,
        'radius_deg': 0.8,
    },
}

TARGET_TILE_OVERRIDES: dict[str, dict[int, set[int]]] = {
    'm31': {
        0: {2, 3, 4},
        1: {9, 11, 13, 14, 15, 19},
        2: {8, 9, 11, 39, 45, 47, 53, 55, 58, 59, 61, 62, 63, 79},
        3: {35, 38, 44, 45, 46, 157, 159, 181, 182, 183, 213, 238, 239, 250, 251, 317, 319},
        4: {162, 164, 165, 167, 171, 173, 178, 637, 639, 725, 727, 958, 959, 1002, 1003},
        5: {659, 665, 670},
    },
}

FALLBACK_SURVEY_METADATA = {
    'obs_collection': 'DSS colored',
    'obs_title': 'DSS colored',
    'obs_description': 'Color composition generated by CDS from the Digitized Sky Survey.',
    'obs_copyright': 'Digitized Sky Survey - STScI/NASA, Colored & Healpixed by CDS',
    'hips_copyright': 'CNRS/Unistra',
    'hips_license': 'ODbL-1.0',
    'creator_did': 'ivo://CDS/P/DSS2/color',
    'hips_tile_width': '512',
    'hips_tile_format': 'jpeg',
    'hips_frame': 'equatorial',
    'dataproduct_type': 'image',
    'dataproduct_subtype': 'color',
    'hips_version': '1.4',
}


class ConfirmationRequiredError(PermissionError):
    pass


@dataclass(frozen=True)
class ProofTarget:
    key: str
    label: str
    display_name: str
    ra_deg: float
    dec_deg: float
    radius_deg: float


def mirror_dss_hips_proof(
    *,
    target: str = DEFAULT_TARGET,
    source_root: str = DEFAULT_SOURCE_ROOT,
    raw_root: str | Path = DEFAULT_RAW_ROOT,
    processed_root: str | Path = DEFAULT_PROCESSED_ROOT,
    order_min: int = DEFAULT_ORDER_MIN,
    order_max: int = DEFAULT_ORDER_MAX,
    radius_deg: float | None = None,
    sample_step_deg: float = DEFAULT_SAMPLE_STEP_DEG,
    dry_run: bool = False,
    confirm_download: bool = False,
) -> dict[str, Any]:
    proof_target = get_target(target, radius_deg)
    normalized_source_root = source_root.rstrip('/')
    raw_root_path = Path(raw_root).resolve()
    processed_root_path = Path(processed_root).resolve()
    runtime_ready_root = processed_root_path / RUNTIME_READY_RELATIVE_ROOT

    if order_min < 0 or order_max < order_min:
        raise ValueError('order range must satisfy 0 <= order_min <= order_max')
    if sample_step_deg <= 0:
        raise ValueError('sample_step_deg must be positive')

    selected_tiles = build_disc_tile_plan(
        ra_deg=proof_target.ra_deg,
        dec_deg=proof_target.dec_deg,
        radius_deg=proof_target.radius_deg,
        order_min=order_min,
        order_max=order_max,
        sample_step_deg=sample_step_deg,
    )
    apply_target_tile_overrides(selected_tiles, target=proof_target.key, order_min=order_min, order_max=order_max)
    relative_tile_paths = build_relative_tile_paths(selected_tiles, ext='jpg')
    properties_relative_path = 'properties'
    source_properties_url = f'{normalized_source_root}/properties'
    source_tile_urls = [f'{normalized_source_root}/{relative_path}' for relative_path in relative_tile_paths]

    if not dry_run and is_network_source(normalized_source_root) and not confirm_download:
        raise ConfirmationRequiredError(
            'Network download is blocked by default. Re-run with --confirm-download.'
        )

    if not dry_run:
        shutil.rmtree(raw_root_path, ignore_errors=True)
        shutil.rmtree(runtime_ready_root, ignore_errors=True)

    source_properties_text = None
    source_properties = dict(FALLBACK_SURVEY_METADATA)
    runtime_checksums: dict[str, str] = {}
    tile_sizes: dict[str, int] = {}
    total_bytes = 0

    if not dry_run:
        source_properties_text = read_text_url(source_properties_url)
        source_properties.update(parse_hips_properties(source_properties_text))
        source_properties_path = raw_root_path / 'source/properties.cds'
        source_properties_path.parent.mkdir(parents=True, exist_ok=True)
        source_properties_path.write_text(source_properties_text, encoding='utf-8')

        runtime_properties_text = build_runtime_properties_text(
            source_properties=source_properties,
            proof_target=proof_target,
            order_min=order_min,
            order_max=order_max,
            source_root=normalized_source_root,
        )
        runtime_properties_path = runtime_ready_root / properties_relative_path
        runtime_properties_path.parent.mkdir(parents=True, exist_ok=True)
        runtime_properties_path.write_text(runtime_properties_text, encoding='utf-8')
        runtime_checksums[properties_relative_path] = sha256_bytes(runtime_properties_text.encode('utf-8'))
        total_bytes += runtime_properties_path.stat().st_size

        for relative_path in relative_tile_paths:
            tile_bytes = read_binary_url(f'{normalized_source_root}/{relative_path}')
            raw_tile_path = raw_root_path / 'source' / relative_path
            processed_tile_path = runtime_ready_root / relative_path
            raw_tile_path.parent.mkdir(parents=True, exist_ok=True)
            processed_tile_path.parent.mkdir(parents=True, exist_ok=True)
            raw_tile_path.write_bytes(tile_bytes)
            processed_tile_path.write_bytes(tile_bytes)
            runtime_relative_path = str(RUNTIME_SURVEY_RELATIVE_ROOT / relative_path)
            runtime_checksums[runtime_relative_path] = sha256_bytes(tile_bytes)
            tile_sizes[runtime_relative_path] = len(tile_bytes)
            total_bytes += len(tile_bytes)

    runtime_relative_paths = [str(RUNTIME_SURVEY_RELATIVE_ROOT / properties_relative_path)] + [
        str(RUNTIME_SURVEY_RELATIVE_ROOT / relative_path) for relative_path in relative_tile_paths
    ]
    manifest = {
        'proof_type': 'oras_dss_hips_survey_proof',
        'generated_at': utc_now(),
        'target': {
            'key': proof_target.key,
            'label': proof_target.label,
            'display_name': proof_target.display_name,
            'center_ra_deg': proof_target.ra_deg,
            'center_dec_deg': proof_target.dec_deg,
            'radius_deg': proof_target.radius_deg,
        },
        'source_survey': {
            'name': source_properties.get('obs_title', FALLBACK_SURVEY_METADATA['obs_title']),
            'creator_did': source_properties.get('creator_did', FALLBACK_SURVEY_METADATA['creator_did']),
            'source_root_url': normalized_source_root,
            'properties_url': source_properties_url,
            'tile_url_root': normalized_source_root,
            'license_note': source_properties.get('hips_license', FALLBACK_SURVEY_METADATA['hips_license']),
            'copyright_note': source_properties.get('obs_copyright', FALLBACK_SURVEY_METADATA['obs_copyright']),
            'acceptability_note': 'Official CDS HiPS survey mirrored only through admin/import tooling; runtime stays same-origin only.',
        },
        'source_urls': [source_properties_url] + source_tile_urls,
        'orders_mirrored': sorted(selected_tiles),
        'tile_count': len(relative_tile_paths),
        'byte_count': total_bytes,
        'downloaded': not dry_run,
        'checksums': runtime_checksums,
        'tile_sizes': tile_sizes,
        'generated_runtime_path_plan': {
            'runtime_relative_paths': runtime_relative_paths,
            'vendor_test_skydata_target_root': str(VENDOR_RUNTIME_SURVEY_ROOT),
            'public_runtime_target_root': str(PUBLIC_RUNTIME_SURVEY_ROOT),
            'processed_runtime_ready_root': str(runtime_ready_root),
        },
    }
    manifest_path = processed_root_path / 'manifest.json'
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    write_json(manifest_path, manifest)

    return {
        'manifest_path': str(manifest_path),
        'target': proof_target.key,
        'source_root': normalized_source_root,
        'tile_count': len(relative_tile_paths),
        'byte_count': total_bytes,
        'downloaded': not dry_run,
        'processed_runtime_ready_root': str(runtime_ready_root),
        'runtime_relative_paths': runtime_relative_paths,
    }


def get_target(target: str, radius_override: float | None = None) -> ProofTarget:
    if target not in TARGETS:
        raise ValueError(f'Unsupported target: {target}')
    raw_target = TARGETS[target]
    return ProofTarget(
        key=raw_target['key'],
        label=raw_target['label'],
        display_name=raw_target['display_name'],
        ra_deg=float(raw_target['ra_deg']),
        dec_deg=float(raw_target['dec_deg']),
        radius_deg=float(radius_override if radius_override is not None else raw_target['radius_deg']),
    )


def build_disc_tile_plan(
    *,
    ra_deg: float,
    dec_deg: float,
    radius_deg: float,
    order_min: int,
    order_max: int,
    sample_step_deg: float,
) -> dict[int, list[int]]:
    highest_order_tiles: set[int] = set()
    center_dec_rad = math.radians(dec_deg)
    cos_dec = max(math.cos(center_dec_rad), 0.1)
    padded_radius = radius_deg + sample_step_deg
    dec_value = dec_deg - padded_radius
    while dec_value <= dec_deg + padded_radius + 1e-9:
        dec_offset = dec_value - dec_deg
        circle_term = padded_radius * padded_radius - dec_offset * dec_offset
        if circle_term < 0:
            dec_value += sample_step_deg
            continue
        max_ra_offset = math.sqrt(circle_term) / cos_dec
        ra_step = sample_step_deg / cos_dec
        ra_value = ra_deg - max_ra_offset
        while ra_value <= ra_deg + max_ra_offset + 1e-9:
            highest_order_tiles.add(ang2pix_nest(order_max, ra_value % 360.0, dec_value))
            ra_value += ra_step
        dec_value += sample_step_deg

    highest_order_tiles.add(ang2pix_nest(order_max, ra_deg, dec_deg))

    tile_sets: dict[int, set[int]] = {order: set() for order in range(order_min, order_max + 1)}
    for pix in highest_order_tiles:
        current_pix = pix
        for order in range(order_max, order_min - 1, -1):
            tile_sets[order].add(current_pix)
            current_pix //= 4

    return {order: sorted(tile_sets[order]) for order in range(order_min, order_max + 1)}


def build_relative_tile_paths(selected_tiles: dict[int, list[int]], *, ext: str) -> list[str]:
    relative_paths: list[str] = []
    for order, pix_values in sorted(selected_tiles.items()):
        for pix in pix_values:
            dir_value = (pix // 10000) * 10000
            relative_paths.append(f'Norder{order}/Dir{dir_value}/Npix{pix}.{ext}')
    return relative_paths


def apply_target_tile_overrides(
    selected_tiles: dict[int, list[int]],
    *,
    target: str,
    order_min: int,
    order_max: int,
) -> None:
    override_tiles = TARGET_TILE_OVERRIDES.get(target, {})
    for order, pix_values in override_tiles.items():
        if order < order_min or order > order_max:
            continue
        merged_values = set(selected_tiles.get(order, []))
        merged_values.update(pix_values)
        selected_tiles[order] = sorted(merged_values)


def ang2pix_nest(order: int, ra_deg: float, dec_deg: float) -> int:
    nside = 1 << order
    z = math.sin(math.radians(dec_deg))
    za = abs(z)
    phi = math.radians(ra_deg % 360.0)
    tt = phi / (0.5 * math.pi)

    if za <= 2.0 / 3.0:
        jp = int(math.floor(nside * (0.5 + tt - 0.75 * z)))
        jm = int(math.floor(nside * (0.5 + tt + 0.75 * z)))
        ifp = jp // nside
        ifm = jm // nside
        if ifp == ifm:
            face_num = (ifp % 4) + 4
        elif ifp < ifm:
            face_num = ifp % 4
        else:
            face_num = (ifm % 4) + 8
        ix = jm % nside
        iy = nside - (jp % nside) - 1
    else:
        ntt = min(3, int(math.floor(tt)))
        tp = tt - ntt
        tmp = nside * math.sqrt(3.0 * (1.0 - za))
        jp = min(nside - 1, int(math.floor(tp * tmp)))
        jm = min(nside - 1, int(math.floor((1.0 - tp) * tmp)))
        if z >= 0:
            face_num = ntt
            ix = nside - jm - 1
            iy = nside - jp - 1
        else:
            face_num = ntt + 8
            ix = jp
            iy = jm

    return face_num * nside * nside + interleave_bits(ix, iy)


def interleave_bits(ix: int, iy: int) -> int:
    result = 0
    bit_index = 0
    while ix or iy:
        result |= (ix & 1) << (2 * bit_index)
        result |= (iy & 1) << (2 * bit_index + 1)
        ix >>= 1
        iy >>= 1
        bit_index += 1
    return result


def parse_hips_properties(text: str) -> dict[str, str]:
    properties: dict[str, str] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        properties[key.strip()] = value.strip()
    return properties


def build_runtime_properties_text(
    *,
    source_properties: dict[str, str],
    proof_target: ProofTarget,
    order_min: int,
    order_max: int,
    source_root: str,
) -> str:
    pairs = [
        ('creator_did', source_properties.get('creator_did', FALLBACK_SURVEY_METADATA['creator_did'])),
        ('obs_collection', 'ORAS DSS proof'),
        ('obs_title', f"{proof_target.label} DSS proof"),
        ('obs_description', f"Bounded ORAS-owned HiPS proof around {proof_target.display_name} mirrored from the official CDS DSS colored survey."),
        ('obs_copyright', source_properties.get('obs_copyright', FALLBACK_SURVEY_METADATA['obs_copyright'])),
        ('hips_builder', 'ORAS mirror_dss_hips_proof.py'),
        ('hips_creation_date', utc_now()),
        ('hips_release_date', source_properties.get('hips_release_date', utc_now())),
        ('hips_creator', 'ORAS admin mirror'),
        ('hips_version', source_properties.get('hips_version', FALLBACK_SURVEY_METADATA['hips_version'])),
        ('hips_order', str(order_max)),
        ('hips_order_min', str(order_min)),
        ('hips_frame', source_properties.get('hips_frame', FALLBACK_SURVEY_METADATA['hips_frame'])),
        ('hips_tile_width', source_properties.get('hips_tile_width', FALLBACK_SURVEY_METADATA['hips_tile_width'])),
        ('hips_tile_format', source_properties.get('hips_tile_format', FALLBACK_SURVEY_METADATA['hips_tile_format'])),
        ('dataproduct_type', source_properties.get('dataproduct_type', FALLBACK_SURVEY_METADATA['dataproduct_type'])),
        ('dataproduct_subtype', source_properties.get('dataproduct_subtype', FALLBACK_SURVEY_METADATA['dataproduct_subtype'])),
        ('hips_status', 'private master'),
        ('hips_license', source_properties.get('hips_license', FALLBACK_SURVEY_METADATA['hips_license'])),
        ('hips_copyright', source_properties.get('hips_copyright', FALLBACK_SURVEY_METADATA['hips_copyright'])),
    ]
    return ''.join(f'{key:<22} = {value}\n' for key, value in pairs)


def read_text_url(url: str) -> str:
    with urlopen(url) as response:
        return response.read().decode('utf-8')


def read_binary_url(url: str) -> bytes:
    with urlopen(url) as response:
        return response.read()


def is_network_source(source_root: str) -> bool:
    return urlparse(source_root).scheme in {'http', 'https'}


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace('+00:00', 'Z')


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description='Mirror a bounded DSS HiPS proof into staged ORAS-owned assets')
    parser.add_argument('--target', default=DEFAULT_TARGET, choices=sorted(TARGETS), help='Proof target key')
    parser.add_argument('--source-root', default=DEFAULT_SOURCE_ROOT, help='HiPS survey root URL or file URI')
    parser.add_argument('--order-min', type=int, default=DEFAULT_ORDER_MIN, help='Minimum mirrored HiPS order')
    parser.add_argument('--order-max', type=int, default=DEFAULT_ORDER_MAX, help='Maximum mirrored HiPS order')
    parser.add_argument('--radius-deg', type=float, help='Override target radius in degrees')
    parser.add_argument('--sample-step-deg', type=float, default=DEFAULT_SAMPLE_STEP_DEG, help='Sampling step in degrees for bounded tile selection')
    parser.add_argument('--dry-run', action='store_true', help='Plan the proof without downloading files')
    parser.add_argument('--confirm-download', action='store_true', help='Required for network downloads')
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    report = mirror_dss_hips_proof(
        target=args.target,
        source_root=args.source_root,
        order_min=args.order_min,
        order_max=args.order_max,
        radius_deg=args.radius_deg,
        sample_step_deg=args.sample_step_deg,
        dry_run=args.dry_run,
        confirm_download=args.confirm_download,
    )
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())